import { ApparelCut, Customer, Design, DtfDimension, FabricMaterial, Order, QuantityTierDiscount } from '@/types/database';

export const INITIAL_FABRIC_MATERIALS: FabricMaterial[] = [
  {
    id: 'mat-1',
    name: 'Drifit Milano (Premium)',
    code: 'drifit_milano',
    weight_gsm: 165,
    breathability: 'Ultra Breathable',
    sublimation_base_price: 35.00,
    description: 'Micro-pore zigzag knit texture. Fast drying sweat evaporation, vivid color saturation. Best for pro football & esports jerseys.',
    is_popular: true,
    is_active: true,
    sort_order: 1,
  },
  {
    id: 'mat-2',
    name: 'Drifit Microfiber (Smooth)',
    code: 'drifit_microfiber',
    weight_gsm: 155,
    breathability: 'High',
    sublimation_base_price: 30.00,
    description: 'Silky smooth handfeel, maximum detail for gradients & badges. Great for badminton, running & active wear.',
    is_popular: true,
    is_active: true,
    sort_order: 2,
  },
  {
    id: 'mat-3',
    name: 'Poly-Mesh Honeycomb',
    code: 'poly_mesh_honeycomb',
    weight_gsm: 180,
    breathability: 'Ultra Breathable',
    sublimation_base_price: 38.00,
    description: 'Hexagonal open-hole aeration structure for heavy perspiration sports and basketball jerseys.',
    is_popular: false,
    is_active: true,
    sort_order: 3,
  },
  {
    id: 'mat-4',
    name: 'Spandex Poly-Blend (4-Way)',
    code: 'spandex_poly',
    weight_gsm: 210,
    breathability: 'High',
    sublimation_base_price: 42.00,
    description: 'High-elasticity compression blend with 12% elastane. Ideal for cycling, rashguards, and athletic compression tops.',
    is_popular: false,
    is_active: true,
    sort_order: 4,
  },
  {
    id: 'mat-5',
    name: 'Coolmax Anti-Bacterial Pro',
    code: 'coolmax_antibacterial',
    weight_gsm: 170,
    breathability: 'Ultra Breathable',
    sublimation_base_price: 45.00,
    description: 'Infused with silver-ion antimicrobial yarn. Resists odor buildup and maintains continuous cooling.',
    is_popular: true,
    is_active: true,
    sort_order: 5,
  },
];

export const INITIAL_APPAREL_CUTS: ApparelCut[] = [
  {
    id: 'cut-1',
    name: 'Short Sleeve Standard Crew O-Neck',
    code: 'ss_crew',
    cut_add_on_price: 0,
    description: 'Classic O-Neck collar with standard sleeve cut and double-needle hem.',
    is_active: true,
    sort_order: 1,
  },
  {
    id: 'cut-2',
    name: 'Short Sleeve V-Neck Pro',
    code: 'ss_vneck',
    cut_add_on_price: 2.00,
    description: 'Athletic taped V-Neck collar with crossover front tab.',
    is_active: true,
    sort_order: 2,
  },
  {
    id: 'cut-3',
    name: 'Raglan Sleeve Mobility Cut',
    code: 'raglan_ss',
    cut_add_on_price: 3.00,
    description: 'Continuous diagonal sleeve seam extending to neckline for unrestricted arm swinging mobility.',
    is_active: true,
    sort_order: 3,
  },
  {
    id: 'cut-4',
    name: 'Polo Collar + 3-Button Placket',
    code: 'polo_collar',
    cut_add_on_price: 6.00,
    description: 'Ribbed knit or full-sublimated crisp collar with reinforced button box placket.',
    is_active: true,
    sort_order: 4,
  },
  {
    id: 'cut-5',
    name: 'Long Sleeve Elastic Wrist Cuff',
    code: 'ls_elastic',
    cut_add_on_price: 5.00,
    description: 'Extended full length sleeves with 2-inch ribbed cuff finishing.',
    is_active: true,
    sort_order: 5,
  },
  {
    id: 'cut-6',
    name: 'Oversized Boxy Drop-Shoulder',
    code: 'oversized_box',
    cut_add_on_price: 4.00,
    description: 'Heavy streetwear silhouette with 3cm thick collar rib and dropped shoulders.',
    is_active: true,
    sort_order: 6,
  },
];

export const INITIAL_DTF_DIMENSIONS: DtfDimension[] = [
  {
    id: 'dtf-1',
    name: 'Logo / Pocket Print (10x10 cm)',
    code: 'dtf_pocket',
    dimensions_desc: '10 x 10 cm',
    base_price: 5.00,
    is_meter_rate: false,
    garment_included_base_price: 18.00,
    description: 'Ideal for chest pocket emblems, sleeve crests, collar branding, or cap artwork.',
    is_active: true,
    sort_order: 1,
  },
  {
    id: 'dtf-2',
    name: 'A4 Medium Artwork (21x29.7 cm)',
    code: 'dtf_a4',
    dimensions_desc: '21 x 29.7 cm',
    base_price: 10.00,
    is_meter_rate: false,
    garment_included_base_price: 25.00,
    description: 'Standard center chest or back print size for classic graphic t-shirts and uniforms.',
    is_active: true,
    sort_order: 2,
  },
  {
    id: 'dtf-3',
    name: 'A3 Large Statement (30x42 cm)',
    code: 'dtf_a3',
    dimensions_desc: '30 x 42 cm',
    base_price: 16.00,
    is_meter_rate: false,
    garment_included_base_price: 32.00,
    description: 'Oversized bold front/back artwork with vivid gradient saturation on tees and hoodies.',
    is_active: true,
    sort_order: 3,
  },
  {
    id: 'dtf-4',
    name: 'A2 Poster Jumbo (42x59.4 cm)',
    code: 'dtf_a2',
    dimensions_desc: '42 x 59.4 cm',
    base_price: 26.00,
    is_meter_rate: false,
    garment_included_base_price: 45.00,
    description: 'Maximum coverage print spanning chest to bottom hem or full back canvas.',
    is_active: true,
    sort_order: 4,
  },
  {
    id: 'dtf-5',
    name: 'Gang Sheet Roll (58x100 cm per Meter)',
    code: 'dtf_meter',
    dimensions_desc: '58 x 100 cm Roll',
    base_price: 32.00,
    is_meter_rate: true,
    garment_included_base_price: 0,
    description: 'Bulk print-on-demand transfer film roll. Fit unlimited logos and graphics within 58cm width.',
    is_active: true,
    sort_order: 5,
  },
];

export const INITIAL_QUANTITY_TIERS: QuantityTierDiscount[] = [
  { id: 'tier-1', tier_label: 'Sample (1-5 Pcs)', min_qty: 1, max_qty: 5, discount_percentage: 0 },
  { id: 'tier-2', tier_label: 'Squad Pack (6-12 Pcs)', min_qty: 6, max_qty: 12, discount_percentage: 5 },
  { id: 'tier-3', tier_label: 'Team Pack (13-24 Pcs)', min_qty: 13, max_qty: 24, discount_percentage: 10 },
  { id: 'tier-4', tier_label: 'Club Pack (25-50 Pcs)', min_qty: 25, max_qty: 50, discount_percentage: 15 },
  { id: 'tier-5', tier_label: 'Bulk Tier (51-100 Pcs)', min_qty: 51, max_qty: 100, discount_percentage: 20 },
  { id: 'tier-6', tier_label: 'Enterprise (101+ Pcs)', min_qty: 101, max_qty: null, discount_percentage: 25 },
];

export const INITIAL_DESIGNS: Design[] = [
  {
    id: 'des-1',
    title: 'Jersi Sukan Sublimasi E-Sports & Kelab',
    category: 'Jersi Sukan',
    print_type: 'sublimation',
    thumbnail_url: '/images/prod_sportswear.webp',
    mockup_front_url: '/images/prod_sportswear.webp',
    mockup_back_url: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&auto=format&fit=crop&q=80',
    description: 'Corak geometri moden berteknologi tinggi untuk pasukan esport, futsal dan kelab sukan.',
    tags: ['jersi', 'esports', 'sublimasi', 'sukan'],
    is_featured: true,
    is_active: true,
  },
  {
    id: 'des-2',
    title: 'Set Jersi Bola Sepak Apex Classic',
    category: 'Jersi Sukan',
    print_type: 'sublimation',
    thumbnail_url: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=800&auto=format&fit=crop&q=80',
    mockup_front_url: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=800&auto=format&fit=crop&q=80',
    mockup_back_url: 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?w=800&auto=format&fit=crop&q=80',
    description: 'Reka bentuk gelombang moden dengan kain dryfit milano serap peluh untuk perlawanan rasmi.',
    tags: ['bola', 'futsal', 'sublimasi', 'jersi'],
    is_featured: true,
    is_active: true,
  },
  {
    id: 'des-3',
    title: 'Baju T-Shirt Cetakan DTF Streetwear',
    category: 'T-Shirt',
    print_type: 'dtf',
    thumbnail_url: '/images/prod_tshirt.webp',
    mockup_front_url: '/images/prod_tshirt.webp',
    mockup_back_url: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&auto=format&fit=crop&q=80',
    description: 'Cetakan stiker DTF elastik berkualiti tinggi di atas baju cotton 24s 100% combed.',
    tags: ['dtf', 'streetwear', 'cotton', 'tshirt'],
    is_featured: true,
    is_active: true,
  },
  {
    id: 'des-4',
    title: 'Hoodie Fleece DTF Typography',
    category: 'Hoodie',
    print_type: 'dtf',
    thumbnail_url: '/images/prod_merchandise.webp',
    mockup_front_url: '/images/prod_merchandise.webp',
    mockup_back_url: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=800&auto=format&fit=crop&q=80',
    description: 'Cetakan DTF bersaiz besar di bahagian belakang hoodie fleece tebal dan lembut.',
    tags: ['hoodie', 'streetwear', 'dtf'],
    is_featured: false,
    is_active: true,
  },
  {
    id: 'des-5',
    title: 'AeroFlow Pro Cycling Jersey',
    category: 'Jersi Sukan',
    print_type: 'sublimation',
    thumbnail_url: '/images/prod_sportswear.webp',
    mockup_front_url: '/images/prod_sportswear.webp',
    mockup_back_url: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&auto=format&fit=crop&q=80',
    description: 'Topographic contour print with 3-pocket back panel sublimation cut for road and gravel cyclists.',
    tags: ['cycling', 'aerodynamic', 'contour', 'sublimation'],
    is_featured: true,
    is_active: true,
  },
  {
    id: 'des-6',
    title: 'Signature Club Pique Polo',
    category: 'Sulaman Khas',
    print_type: 'both',
    thumbnail_url: '/images/prod_embroidery.webp',
    mockup_front_url: '/images/prod_embroidery.webp',
    mockup_back_url: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&auto=format&fit=crop&q=80',
    description: 'Sublimated patterned collar with custom DTF chest crest badge for golf, corporate & staff wear.',
    tags: ['polo', 'corporate', 'golf', 'sulaman'],
    is_featured: false,
    is_active: true,
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [];

export const INITIAL_ORDERS: Order[] = [];

// ==========================================
// INITIAL CMS DATA SEEDS
// ==========================================

export const INITIAL_CMS_HERO_BANNERS = [
  {
    id: 'hero-1',
    image_url: '/hero1.webp',
    status_pill: 'Harga Direct Kilang',
    tag_text: 'Pengeluar No. 1 Malaysia',
    title: 'Kilang Cetak Jersi Sublimasi & Baju DTF',
    button_text: 'Lihat Katalog',
    button_link: '/catalog',
    sort_order: 1,
    is_active: true,
  },
  {
    id: 'hero-2',
    image_url: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=1200&auto=format&fit=crop&q=80',
    status_pill: 'Sublimasi Penuh HD',
    tag_text: 'Sukan, E-Sukan & Korporat',
    title: 'Jersi Sublimasi Kustom Berkualiti',
    button_text: 'Tempah Jersi',
    button_link: '/catalog?type=sublimation',
    sort_order: 2,
    is_active: true,
  },
  {
    id: 'hero-3',
    image_url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=1200&auto=format&fit=crop&q=80',
    status_pill: 'Tiada Minimum Order',
    tag_text: 'Kapas 100% & Dakwat Jepun',
    title: 'Cetakan Baju DTF Berkualiti Tinggi',
    button_text: 'Katalog DTF',
    button_link: '/catalog?type=dtf',
    sort_order: 3,
    is_active: true,
  },
];

export const INITIAL_CMS_TRUST_BADGES = [
  {
    id: 'direct-kilang',
    title: 'Harga Direct Kilang',
    desc: 'Tanpa orang tengah · Lebih jimat & telus',
    pill: 'Direct Kilang',
    icon_name: 'Building2',
    color_theme: 'sky',
    sort_order: 1,
    is_active: true,
  },
  {
    id: 'no-moq',
    title: 'Tiada Minimum Order',
    desc: 'Kustom & DTF · 1 helai pun kami buat',
    pill: 'Bebas MOQ',
    icon_name: 'PackageCheck',
    color_theme: 'indigo',
    sort_order: 2,
    is_active: true,
  },
  {
    id: 'siap-pantas',
    title: 'Siap Pantas 5-7 Hari',
    desc: 'Produksi pantas · Penghantaran tepat masa',
    pill: 'Express Siap',
    icon_name: 'Clock',
    color_theme: 'sky',
    sort_order: 3,
    is_active: true,
  },
  {
    id: 'qc-guarantee',
    title: 'Jaminan 1-to-1 QC',
    desc: 'Pemeriksaan kualiti rapi · Ganti jika rosak',
    pill: '100% QC Pass',
    icon_name: 'ShieldCheck',
    color_theme: 'emerald',
    sort_order: 4,
    is_active: true,
  },
];

export const INITIAL_CMS_SERVICES = [
  {
    id: 'sublimation',
    category: 'Sublimasi Penuh',
    title: 'Jersi Sublimasi',
    headline: 'Corak tanpa batasan untuk kelab sukan anda.',
    highlight: 'Kain DryFit • Warna Kekal',
    price_prefix: 'Bermula',
    price_amount: 'RM28',
    price_unit: '/ helai',
    image_url: '/images/prod_sportswear.webp',
    href: '/catalog?type=sublimation',
    sort_order: 1,
    is_active: true,
    details: [
      {
        title: 'Ketahanan warna tanpa luntur.',
        description: 'Teknologi cetakan sublimasi haba tinggi menyerap terus ke dalam serat fabrik Microfiber Eyelet. Warna kekal terang, tajam, dan tidak merekah walaupun dibasuh berulang kali.',
      },
      {
        title: 'Kesejukan & pengudaraan optimum.',
        description: 'Fabrik quick-dry berliang mikro direka khas untuk atlet dan sukan lasak. Memastikan penyejukan badan maksimum sepanjang hari.',
      },
      {
        title: 'Kustom sepenuhnya.',
        description: 'Pilihan kolar V-neck, Roundneck, atau Polo dengan cetakan nama dan nombor jersi tanpa had caj tambahan.',
      },
    ],
  },
  {
    id: 'tshirt',
    category: 'Cetakan DTF',
    title: 'Cetakan T-Shirt',
    headline: 'Perincian ultra tajam pada kapas premium.',
    highlight: 'Kapas 100% • Warna Tajam',
    price_prefix: 'Bermula',
    price_amount: 'RM18',
    price_unit: '/ helai',
    image_url: '/images/prod_tshirt.webp',
    href: '/catalog?type=dtf',
    sort_order: 2,
    is_active: true,
    details: [
      {
        title: 'Hasil cetakan sehalus fotografi.',
        description: 'Menggunakan dakwat DTF gred industri Jepun dengan lapisan serbuk TPU premium, menghasilkan cetakan yang elastik dan lembut disentuh.',
      },
      {
        title: 'Kapas 100% Combed Cotton.',
        description: 'Pilihan baju kapas berkualiti tinggi 190gsm - 220gsm yang selesa, sejuk, dan tahan lasak selepas basuhan.',
      },
      {
        title: 'Tiada had kuantiti minimum.',
        description: 'Sesuai untuk tempahan kumpulan kecil, baju kelas, acara keluarga, mahupun edisi terhad jenama anda.',
      },
    ],
  },
  {
    id: 'merchandise',
    category: 'Cenderamata',
    title: 'Cenderamata',
    headline: 'Hadiah korporat eksklusif berjenama.',
    highlight: 'Lanyard, Beg & Cawan',
    price_prefix: 'Bermula',
    price_amount: 'RM5',
    price_unit: '/ unit',
    image_url: '/images/prod_merchandise.webp',
    href: '/catalog?type=merchandise',
    sort_order: 3,
    is_active: true,
    details: [
      {
        title: 'Lanyard Sublimasi HD.',
        description: 'Tali lanyard berkualiti tinggi dengan cetakan dua sisi warna penuh dan cangkuk besi tahan karat tebal.',
      },
      {
        title: 'Tote Bag & Beg Kasut Kanvas.',
        description: 'Pilihan cenderamata tahan lasak untuk program orientasi, sukan universiti, dan cenderamata persidangan.',
      },
      {
        title: 'Mug Seramik & Botol Air Termos.',
        description: 'Cetakan logo berdefinisi tinggi untuk hadiah VIP dan acara penghargaan pekerja.',
      },
    ],
  },
  {
    id: 'embroidery',
    category: 'Sulaman Komputer',
    title: 'Sulaman Logo',
    headline: 'Ketelitian jahitan kemas berprofil tinggi.',
    highlight: 'Benang Jepun • Tahan Lasak',
    price_prefix: 'Bermula',
    price_amount: 'RM6',
    price_unit: '/ logo',
    image_url: '/images/prod_embroidery.webp',
    href: '/catalog?type=embroidery',
    sort_order: 4,
    is_active: true,
    details: [
      {
        title: 'Mesin Sulaman Berkomputer Multi-Head.',
        description: 'Ketepatan tinggi sehingga ribuan jahitan mikro bagi merealisasikan logo jata sekolah, institusi, dan syarikat.',
      },
      {
        title: 'Sulaman 3D Timbul (Puff Embroidery).',
        description: 'Sesuai untuk topi snapback, jaket bomber, dan lencana korporat eksklusif.',
      },
      {
        title: 'Ketahanan Benang Tidak Putus.',
        description: 'Menggunakan benang polyester berkualiti tinggi yang tahan luntur warna serta tidak reput apabila dicuci.',
      },
    ],
  },
];

export const INITIAL_CMS_PRODUCTION_VIDEOS = [
  {
    id: 'vid-sublimation',
    category: 'Sublimasi Penuh',
    title: 'Cetakan Definisi Tinggi',
    thumbnail_url: '/images/prod_sportswear.webp',
    youtube_id: 'LXb3EKWsInQ',
    sort_order: 1,
    is_active: true,
  },
  {
    id: 'vid-dtf',
    category: 'Cetakan DTF',
    title: 'Teknologi Dakwat Jepun',
    thumbnail_url: '/images/prod_tshirt.webp',
    youtube_id: 'kJQP7kiw5Fk',
    sort_order: 2,
    is_active: true,
  },
  {
    id: 'vid-embroidery',
    category: 'Sulaman Berkomputer',
    title: 'Ketumpatan Jahitan Tajam',
    thumbnail_url: '/images/prod_embroidery.webp',
    youtube_id: '9bZkp7q19f0',
    sort_order: 3,
    is_active: true,
  },
  {
    id: 'vid-merchandise',
    category: 'Cenderamata Syarikat',
    title: 'Kualiti Kemasan Eksekutif',
    thumbnail_url: '/images/prod_merchandise.webp',
    youtube_id: '3JZ_D3ELwOQ',
    sort_order: 4,
    is_active: true,
  },
];

export const INITIAL_CMS_PRODUCTION_GALLERY = [
  {
    id: 'gal-1',
    title: 'Jersi Bola Sepak Harimau FC',
    category: 'Sublimasi Penuh',
    fabric: 'Drifit Milano 165 GSM • Kolar V-Pro',
    image_url: '/images/prod_sportswear.webp',
    client: '50 helai • FC Harimau Selangor',
    tag: 'Full Sublimation',
    sort_order: 1,
    is_active: true,
  },
  {
    id: 'gal-2',
    title: 'Jersi E-Sports Valkyrie HD',
    category: 'Sublimasi Penuh HD',
    fabric: 'Microfiber Smooth • Potongan Raglan',
    image_url: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=1000&auto=format&fit=crop&q=80',
    client: '25 helai • Valkyrie MY E-Sports',
    tag: 'Esports Pro',
    sort_order: 2,
    is_active: true,
  },
  {
    id: 'gal-3',
    title: 'Baju T-Shirt Streetwear Neo-Tokyo',
    category: 'Cetakan DTF HD',
    fabric: 'Heavyweight Cotton 24s • Saiz Cetak A3',
    image_url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=1000&auto=format&fit=crop&q=80',
    client: '80 helai • Neo Apparel Store',
    tag: 'DTF Transfer',
    sort_order: 3,
    is_active: true,
  },
  {
    id: 'gal-4',
    title: 'Jersi Larian AeroFlow Marathon',
    category: 'Sublimasi Penuh',
    fabric: 'Poly-Mesh Honeycomb • Ultra Breathable',
    image_url: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?w=1000&auto=format&fit=crop&q=80',
    client: '120 helai • KL Running Squad',
    tag: 'Running Kit',
    sort_order: 4,
    is_active: true,
  },
  {
    id: 'gal-5',
    title: 'Hoodie Fleece Heavyweight Glitch',
    category: 'DTF Elastomeric',
    fabric: 'Cotton Fleece 320 GSM • Cetakan Belakang Jumbo A2',
    image_url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=1000&auto=format&fit=crop&q=80',
    client: '35 helai • Glitch Society KL',
    tag: 'Heavy Hoodie',
    sort_order: 5,
    is_active: true,
  },
  {
    id: 'gal-6',
    title: 'Baju Polo Pique Kelab Korporat',
    category: 'Sublimasi & DTF',
    fabric: 'Pique Poly-Blend • Kolar Butang & Lencana Dada',
    image_url: 'https://images.unsplash.com/photo-1625910513413-7a718797f1df?w=1000&auto=format&fit=crop&q=80',
    client: '60 helai • Apex Engineering',
    tag: 'Corporate Polo',
    sort_order: 6,
    is_active: true,
  },
];

export const INITIAL_CMS_TESTIMONIALS = [
  {
    id: 'testi-1',
    name: 'Ahmad Faizal',
    location: 'Kuala Lumpur',
    initial: 'A',
    avatar_bg: 'bg-blue-100',
    avatar_text: 'text-blue-600',
    platform: 'google' as const,
    rating: 5,
    review: '"Baju sampai cepat, design cantik & kain berkualiti! Dah order 3 kali untuk team futsal, terus repeat order. Servis memang padu."',
    is_active: true,
  },
  {
    id: 'testi-2',
    name: 'Nurul Izzah',
    location: 'Shah Alam',
    initial: 'N',
    avatar_bg: 'bg-rose-100',
    avatar_text: 'text-rose-600',
    platform: 'tiktok' as const,
    rating: 5,
    review: '"Sublimasi jersi netball sekolah kami memang meletop warna dia! Halus gila printing, cikgu dan student semua puas hati."',
    is_active: true,
  },
  {
    id: 'testi-3',
    name: 'Hafizuddin Radzi',
    location: 'Johor Bahru',
    initial: 'H',
    avatar_bg: 'bg-blue-100',
    avatar_text: 'text-blue-700',
    platform: 'facebook' as const,
    rating: 5,
    review: '"Tempah baju polo sulam kolar untuk 50 staf syarikat. Jahitan sulam logo tajam sangat, material sejuk sedap pakai pergi event."',
    is_active: true,
  },
  {
    id: 'testi-4',
    name: 'Danial Hakim',
    location: 'Pulau Pinang',
    initial: 'D',
    avatar_bg: 'bg-amber-100',
    avatar_text: 'text-amber-600',
    platform: 'instagram' as const,
    rating: 5,
    review: '"DTF print baju event running kelab kami tak tanggal lepas banyak kali basuh. Kualiti memang terbaik, penghantaran 4 hari dah sampai."',
    is_active: true,
  },
];

export const INITIAL_CMS_SLOGAN_QUOTE = {
  headline: 'Anda bayangkan,',
  highlight_text: 'Kami Jadikan Realiti.',
  question_text: 'Anda Design atau sekadar lakaran?',
  description_text: 'Hantar kepada kami. Kami bantu ubah idea anda menjadi baju sublimation yang nampak WOW dan menepati citarasa anda.',
  button_text: 'Hantar Idea / Lakaran Sekarang →',
  whatsapp_message: 'Hai SFV Apparel, saya ada lakaran/idea rekaan baju yang ingin dijadikan realiti.',
};

export const INITIAL_CMS_COMPANY_SETTINGS = {
  company_name: 'SFV Ventures Marketing',
  brand_name: 'SFV APPAREL',
  registration_number: '202303194821 (003492811-M)',
  tagline: 'Pakar pembuatan jersi sublimasi penuh, cetakan DTF & sulaman pakaian kustom berkualiti tinggi di Malaysia.',
  phone: '+62 812-6006-6616',
  whatsapp_number: '6281260066616',
  whatsapp_default_message: 'Hai SFV Apparel, saya ingin bertanya tentang tempahan kustom baju.',
  email: 'sales@sfvapparel.my',
  address: 'No 28-1, Jalan Prima Saujana 2/D, Taman Prima Saujana, 43000 Kajang, Selangor, Malaysia',
  working_hours: 'Isnin - Jumaat: 9.00 AM - 6.00 PM | Sabtu: 9.00 AM - 1.00 PM',
  website_url: 'https://sfvapparel.my',
  telegram_catalog_url: 'https://t.me/sfvapparelcatalog',
  facebook_url: 'https://www.facebook.com/sfvapparel/',
  instagram_url: 'https://www.instagram.com/sfv.apparel/',
  tiktok_url: 'https://www.tiktok.com/@sfvapparel',
  developer_name: 'AYEZZ Global',
  developer_url: 'https://ayezz.com',
};

export const INITIAL_CMS_POLICIES = {
  privacy: {
    id: 'privacy' as const,
    badge: 'Polisi Privasi',
    title: 'Dasar Privasi & Keselamatan Data Pelanggan',
    description: 'Kami menghormati dan melindungi data peribadi anda selaras dengan Akta Perlindungan Data Peribadi (PDPA) 2010 Malaysia.',
    sections: [
      {
        heading: '1. Pengumpulan Maklumat Peribadi',
        text: 'Kami hanya mengumpulkan maklumat yang diperlukan untuk memproses pesanan anda seperti nama, nombor telefon WhatsApp, alamat penghantaran, dan fail artwork rekaan anda.',
      },
      {
        heading: '2. Penggunaan Data Pesanan',
        text: 'Maklumat anda hanya digunakan untuk tujuan pengeluaran jersi, penghantaran kurier, dan pengemaskinian status pesanan.',
      },
      {
        heading: '3. Kerahsiaan Rekaan (Artwork Confidentiality)',
        text: 'Semua reka bentuk kustom dan logo rasmi kelab/syarikat anda tidak akan dijual atau dicetak untuk pihak ketiga tanpa izin bertulis daripada anda.',
      },
    ],
  },
  terms: {
    id: 'terms' as const,
    badge: 'Terma & Syarat',
    title: 'Terma & Syarat Perkhidmatan Tempahan Kustom',
    description: 'Sila baca syarat-syarat perkhidmatan ini sebelum mengesahkan pesanan pengeluaran jersi kustom anda.',
    sections: [
      {
        heading: '1. Pengesahan Mockup Reka Bentuk',
        text: 'Pelanggan bertanggungjawab menyemak ejaan nama, nombor jersi, logo penaja, dan carta saiz sebelum memberi kelulusan akhir mockup digital.',
      },
      {
        heading: '2. Deposit & Pembayaran',
        text: 'Produksi kilang hanya akan dimulakan setelah deposit tempahan yang dipersetujui disahkan diterima oleh akaun rasmi SFV Ventures Marketing.',
      },
      {
        heading: '3. Pindaan Selepas Cetakan',
        text: 'Sebarang pindaan pada rekaan atau senarai saiz selepas proses cetakan bermula mungkin akan dikenakan caj kos pengeluaran semula.',
      },
      {
        heading: '4. Hak Cipta Reka Bentuk',
        text: 'Pelanggan menjamin bahawa semua logo dan imej yang dibekalkan untuk dicetak adalah hak milik sah atau mempunyai permit/kebenaran penggunaan yang sah.',
      },
    ],
  },
  warranty: {
    id: 'warranty' as const,
    badge: 'Jaminan Kualiti',
    title: 'Polisi Jaminan & Pemulangan (1-to-1 Replacement)',
    description: 'Kami memberi keutamaan penuh kepada kepuasan pelanggan dengan prosedur kawalan kualiti (QC) berstandard tinggi.',
    sections: [
      {
        heading: '1. Jaminan Kualiti Fabrik & Cetakan',
        text: 'Kami menjamin cetakan warna jersi sublimasi penuh adalah tajam, tidak luntur, dan jahitan kemas berstandard sukan profesional.',
      },
      {
        heading: '2. Gantian 1-ke-1 (Defect Replacement)',
        text: 'Sekiranya terdapat kecacatan ketara akibat kesilapan kilang kami (seperti tersalah saiz dari senarai disahkan atau kerosakan fabrik), kami akan menggantikan item tersebut 1-ke-1 secara percuma.',
      },
      {
        heading: '3. Tempoh Laporan Kecacatan',
        text: 'Sebarang tuntutan kecacatan hendaklah dilaporkan kepada pihak khidmat pelanggan kami dalam tempoh 7 hari selepas bungkusan pesanan diterima.',
      },
    ],
  },
  shipping: {
    id: 'shipping' as const,
    badge: 'Polisi Penghantaran',
    title: 'Dasar Penghantaran & Tempoh Pengeluaran',
    description: 'Maklumat berkaitan tempoh siap, pembungkusan rapi, dan kaedah penghantaran ke seluruh Malaysia & Singapura.',
    sections: [
      {
        heading: '1. Tempoh Siap Pengeluaran',
        text: 'Tempoh siap piawai kilang adalah 5 hingga 9 hari bekerja selepas reka bentuk mockup diluluskan secara rasmi oleh pelanggan.',
      },
      {
        heading: '2. Rakan Kurier Rasmi',
        text: 'Penghantaran dibuat menggunakan rakan kurier dipercayai seperti PosLaju, J&T Express, dan NinjaVan dengan nombor penjejakan (tracking number) masa nyata.',
      },
      {
        heading: '3. Kawasan Liputan Penghantaran',
        text: 'Kami menyediakan perkhidmatan penghantaran pantas ke seluruh Semenanjung Malaysia, Sabah, Sarawak, Labuan, dan Singapura.',
      },
    ],
  },
};

export const THEME_PRESETS = {
  hybrid: {
    preset: 'hybrid' as const,
    header_bg: '#00BDFF',
    header_style: 'solid_blue' as const,
    header_logo_mode: 'inverted_white' as const,
    bottom_nav_bg: 'rgba(255, 255, 255, 0.95)',
    bottom_nav_style: 'glass_light' as const,
    bottom_nav_active_color: '#00BDFF',
    bottom_nav_inactive_color: '#94A3B8',
    primary_accent_color: '#00BDFF',
    whatsapp_fab_bg: '#25D366',
  },
  clean_white: {
    preset: 'clean_white' as const,
    header_bg: '#FFFFFF',
    header_style: 'frosted_white' as const,
    header_logo_mode: 'original_blue' as const,
    bottom_nav_bg: 'rgba(255, 255, 255, 0.95)',
    bottom_nav_style: 'glass_light' as const,
    bottom_nav_active_color: '#00BDFF',
    bottom_nav_inactive_color: '#94A3B8',
    primary_accent_color: '#00BDFF',
    whatsapp_fab_bg: '#25D366',
  },
  full_blue: {
    preset: 'full_blue' as const,
    header_bg: '#00BDFF',
    header_style: 'solid_blue' as const,
    header_logo_mode: 'inverted_white' as const,
    bottom_nav_bg: '#00BDFF',
    bottom_nav_style: 'solid_blue' as const,
    bottom_nav_active_color: '#FFFFFF',
    bottom_nav_inactive_color: '#93C5FD',
    primary_accent_color: '#00BDFF',
    whatsapp_fab_bg: '#25D366',
  },
};

export const INITIAL_CMS_THEME_SETTINGS = THEME_PRESETS.clean_white;



