import { ApparelCut, Customer, Design, DtfDimension, FabricMaterial, Order, QuantityTierDiscount } from '@/types/database';

export const INITIAL_FABRIC_MATERIALS: FabricMaterial[] = [
  {
    id: 'mat-1',
    name: 'Drifit Milano (Premium)',
    code: 'drifit_milano',
    weight_gsm: 165,
    breathability: 'Ultra Breathable',
    sublimation_base_price: 35.00,
    description: 'Micro-pore zigzag knit texture. Fast drying sweat evaporation, vivid color saturation. Best for pro football & esports jerseys.',
    is_popular: true,
    is_active: true,
    sort_order: 1,
  },
  {
    id: 'mat-2',
    name: 'Drifit Microfiber (Smooth)',
    code: 'drifit_microfiber',
    weight_gsm: 155,
    breathability: 'High',
    sublimation_base_price: 30.00,
    description: 'Silky smooth handfeel, maximum detail for gradients & badges. Great for badminton, running & active wear.',
    is_popular: true,
    is_active: true,
    sort_order: 2,
  },
  {
    id: 'mat-3',
    name: 'Poly-Mesh Honeycomb',
    code: 'poly_mesh_honeycomb',
    weight_gsm: 180,
    breathability: 'Ultra Breathable',
    sublimation_base_price: 38.00,
    description: 'Hexagonal open-hole aeration structure for heavy perspiration sports and basketball jerseys.',
    is_popular: false,
    is_active: true,
    sort_order: 3,
  },
  {
    id: 'mat-4',
    name: 'Spandex Poly-Blend (4-Way)',
    code: 'spandex_poly',
    weight_gsm: 210,
    breathability: 'High',
    sublimation_base_price: 42.00,
    description: 'High-elasticity compression blend with 12% elastane. Ideal for cycling, rashguards, and athletic compression tops.',
    is_popular: false,
    is_active: true,
    sort_order: 4,
  },
  {
    id: 'mat-5',
    name: 'Coolmax Anti-Bacterial Pro',
    code: 'coolmax_antibacterial',
    weight_gsm: 170,
    breathability: 'Ultra Breathable',
    sublimation_base_price: 45.00,
    description: 'Infused with silver-ion antimicrobial yarn. Resists odor buildup and maintains continuous cooling.',
    is_popular: true,
    is_active: true,
    sort_order: 5,
  },
];

export const INITIAL_APPAREL_CUTS: ApparelCut[] = [
  {
    id: 'cut-1',
    name: 'Short Sleeve Standard Crew O-Neck',
    code: 'ss_crew',
    cut_add_on_price: 0,
    description: 'Classic O-Neck collar with standard sleeve cut and double-needle hem.',
    is_active: true,
    sort_order: 1,
  },
  {
    id: 'cut-2',
    name: 'Short Sleeve V-Neck Pro',
    code: 'ss_vneck',
    cut_add_on_price: 2.00,
    description: 'Athletic taped V-Neck collar with crossover front tab.',
    is_active: true,
    sort_order: 2,
  },
  {
    id: 'cut-3',
    name: 'Raglan Sleeve Mobility Cut',
    code: 'raglan_ss',
    cut_add_on_price: 3.00,
    description: 'Continuous diagonal sleeve seam extending to neckline for unrestricted arm swinging mobility.',
    is_active: true,
    sort_order: 3,
  },
  {
    id: 'cut-4',
    name: 'Polo Collar + 3-Button Placket',
    code: 'polo_collar',
    cut_add_on_price: 6.00,
    description: 'Ribbed knit or full-sublimated crisp collar with reinforced button box placket.',
    is_active: true,
    sort_order: 4,
  },
  {
    id: 'cut-5',
    name: 'Long Sleeve Elastic Wrist Cuff',
    code: 'ls_elastic',
    cut_add_on_price: 5.00,
    description: 'Extended full length sleeves with 2-inch ribbed cuff finishing.',
    is_active: true,
    sort_order: 5,
  },
  {
    id: 'cut-6',
    name: 'Oversized Boxy Drop-Shoulder',
    code: 'oversized_box',
    cut_add_on_price: 4.00,
    description: 'Heavy streetwear silhouette with 3cm thick collar rib and dropped shoulders.',
    is_active: true,
    sort_order: 6,
  },
];

export const INITIAL_DTF_DIMENSIONS: DtfDimension[] = [
  {
    id: 'dtf-1',
    name: 'Logo / Pocket Print (10x10 cm)',
    code: 'dtf_pocket',
    dimensions_desc: '10 x 10 cm',
    base_price: 5.00,
    is_meter_rate: false,
    garment_included_base_price: 18.00,
    description: 'Ideal for chest pocket emblems, sleeve crests, collar branding, or cap artwork.',
    is_active: true,
    sort_order: 1,
  },
  {
    id: 'dtf-2',
    name: 'A4 Medium Artwork (21x29.7 cm)',
    code: 'dtf_a4',
    dimensions_desc: '21 x 29.7 cm',
    base_price: 10.00,
    is_meter_rate: false,
    garment_included_base_price: 25.00,
    description: 'Standard center chest or back print size for classic graphic t-shirts and uniforms.',
    is_active: true,
    sort_order: 2,
  },
  {
    id: 'dtf-3',
    name: 'A3 Large Statement (30x42 cm)',
    code: 'dtf_a3',
    dimensions_desc: '30 x 42 cm',
    base_price: 16.00,
    is_meter_rate: false,
    garment_included_base_price: 32.00,
    description: 'Oversized bold front/back artwork with vivid gradient saturation on tees and hoodies.',
    is_active: true,
    sort_order: 3,
  },
  {
    id: 'dtf-4',
    name: 'A2 Poster Jumbo (42x59.4 cm)',
    code: 'dtf_a2',
    dimensions_desc: '42 x 59.4 cm',
    base_price: 26.00,
    is_meter_rate: false,
    garment_included_base_price: 45.00,
    description: 'Maximum coverage print spanning chest to bottom hem or full back canvas.',
    is_active: true,
    sort_order: 4,
  },
  {
    id: 'dtf-5',
    name: 'Gang Sheet Roll (58x100 cm per Meter)',
    code: 'dtf_meter',
    dimensions_desc: '58 x 100 cm Roll',
    base_price: 32.00,
    is_meter_rate: true,
    garment_included_base_price: 0,
    description: 'Bulk print-on-demand transfer film roll. Fit unlimited logos and graphics within 58cm width.',
    is_active: true,
    sort_order: 5,
  },
];

export const INITIAL_QUANTITY_TIERS: QuantityTierDiscount[] = [
  { id: 'tier-1', tier_label: 'Sample (1-5 Pcs)', min_qty: 1, max_qty: 5, discount_percentage: 0 },
  { id: 'tier-2', tier_label: 'Squad Pack (6-12 Pcs)', min_qty: 6, max_qty: 12, discount_percentage: 5 },
  { id: 'tier-3', tier_label: 'Team Pack (13-24 Pcs)', min_qty: 13, max_qty: 24, discount_percentage: 10 },
  { id: 'tier-4', tier_label: 'Club Pack (25-50 Pcs)', min_qty: 25, max_qty: 50, discount_percentage: 15 },
  { id: 'tier-5', tier_label: 'Bulk Tier (51-100 Pcs)', min_qty: 51, max_qty: 100, discount_percentage: 20 },
  { id: 'tier-6', tier_label: 'Enterprise (101+ Pcs)', min_qty: 101, max_qty: null, discount_percentage: 25 },
];

export const INITIAL_DESIGNS: Design[] = [
  {
    id: 'des-1',
    title: 'Jersi Sukan Sublimasi Cyber Pro',
    category: 'Jersi Sukan',
    print_type: 'sublimation',
    thumbnail_url: '/images/prod_sportswear.jpg',
    mockup_front_url: '/images/prod_sportswear.jpg',
    mockup_back_url: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&auto=format&fit=crop&q=80',
    description: 'Corak geometri moden berteknologi tinggi untuk pasukan esport, futsal dan kelab sukan.',
    tags: ['jersi', 'esports', 'sublimasi', 'sukan'],
    is_featured: true,
    is_active: true,
  },
  {
    id: 'des-2',
    title: 'Set Jersi Bola Sepak Apex Classic',
    category: 'Jersi Sukan',
    print_type: 'sublimation',
    thumbnail_url: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=800&auto=format&fit=crop&q=80',
    mockup_front_url: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=800&auto=format&fit=crop&q=80',
    mockup_back_url: 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?w=800&auto=format&fit=crop&q=80',
    description: 'Reka bentuk gelombang moden dengan kain dryfit milano serap peluh untuk perlawanan rasmi.',
    tags: ['bola', 'futsal', 'sublimasi', 'jersi'],
    is_featured: true,
    is_active: true,
  },
  {
    id: 'des-3',
    title: 'Baju T-Shirt Cetakan DTF Streetwear',
    category: 'T-Shirt',
    print_type: 'dtf',
    thumbnail_url: '/images/prod_tshirt.jpg',
    mockup_front_url: '/images/prod_tshirt.jpg',
    mockup_back_url: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&auto=format&fit=crop&q=80',
    description: 'Cetakan stiker DTF elastik berkualiti tinggi di atas baju cotton 24s 100% combed.',
    tags: ['dtf', 'streetwear', 'cotton', 'tshirt'],
    is_featured: true,
    is_active: true,
  },
  {
    id: 'des-4',
    title: 'Hoodie Fleece DTF Typography',
    category: 'Hoodie',
    print_type: 'dtf',
    thumbnail_url: '/images/prod_merchandise.jpg',
    mockup_front_url: '/images/prod_merchandise.jpg',
    mockup_back_url: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=800&auto=format&fit=crop&q=80',
    description: 'Cetakan DTF bersaiz besar di bahagian belakang hoodie fleece tebal dan lembut.',
    tags: ['hoodie', 'streetwear', 'dtf'],
    is_featured: false,
    is_active: true,
  },
  {
    id: 'des-5',
    title: 'AeroFlow Pro Cycling Jersey',
    category: 'Jersi Sukan',
    print_type: 'sublimation',
    thumbnail_url: '/images/prod_sportswear.jpg',
    mockup_front_url: '/images/prod_sportswear.jpg',
    mockup_back_url: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&auto=format&fit=crop&q=80',
    description: 'Topographic contour print with 3-pocket back panel sublimation cut for road and gravel cyclists.',
    tags: ['cycling', 'aerodynamic', 'contour', 'sublimation'],
    is_featured: true,
    is_active: true,
  },
  {
    id: 'des-6',
    title: 'Signature Club Pique Polo',
    category: 'Sulaman Khas',
    print_type: 'both',
    thumbnail_url: '/images/prod_embroidery.jpg',
    mockup_front_url: '/images/prod_embroidery.jpg',
    mockup_back_url: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&auto=format&fit=crop&q=80',
    description: 'Sublimated patterned collar with custom DTF chest crest badge for golf, corporate & staff wear.',
    tags: ['polo', 'corporate', 'golf', 'sulaman'],
    is_featured: false,
    is_active: true,
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    full_name: 'Muhammad Farhan',
    email: 'farhan.harimau@gmail.com',
    phone: '+60 12-345 6789',
    company_or_team: 'Kelab Esports Harimau MY',
    address: 'No 15, Jalan Ampang',
    city: 'Kuala Lumpur',
    postal_code: '50450',
    total_orders: 4,
    total_spent: 3250.00,
  },
  {
    id: 'cust-2',
    full_name: 'Nur Aisyah Zulaikha',
    email: 'aisyah@selangor-fc.my',
    phone: '+60 17-889 2233',
    company_or_team: 'Akademi Bola Sepak Selangor',
    address: 'Blok B, Seksyen 7',
    city: 'Shah Alam',
    postal_code: '40000',
    total_orders: 2,
    total_spent: 1850.00,
  },
  {
    id: 'cust-3',
    full_name: 'Danial Haziq',
    email: 'danial@johor-cycling.my',
    phone: '+60 19-332 1100',
    company_or_team: 'Southern Riders Cycling Club',
    address: 'No 88, Jalan Sutera',
    city: 'Skudai',
    postal_code: '81300',
    total_orders: 6,
    total_spent: 4650.00,
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-1001',
    order_number: 'SFV-2026-001',
    customer_name: 'Muhammad Farhan',
    customer_email: 'farhan.harimau@gmail.com',
    customer_phone: '+60 12-345 6789',
    print_type: 'sublimation',
    design_id: 'des-1',
    design_title: 'Valkyrie Cyber Esports Jersey',
    mockup_url: '/images/prod_sportswear.jpg',
    fabric_material_id: 'mat-1',
    fabric_name: 'Drifit Milano (Premium)',
    apparel_cut_id: 'cut-3',
    cut_name: 'Raglan Sleeve Mobility Cut',
    sizing_breakdown: { S: 5, M: 10, L: 8, XL: 2 },
    total_quantity: 25,
    raw_unit_price: 38.00,
    discount_percentage: 10,
    final_unit_price: 34.20,
    total_amount: 855.00,
    status: 'in_printing',
    production_notes: 'Custom player gamertags on back in Neon Cyan font.',
    shipping_address: 'No 15, Jalan Ampang, 50450 Kuala Lumpur',
    shipping_courier: 'J&T Express MY',
    tracking_number: 'JNTMY8839201948',
    created_at: new Date(Date.now() - 36 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
  },
  {
    id: 'ord-1002',
    order_number: 'SFV-2026-002',
    customer_name: 'Nur Aisyah Zulaikha',
    customer_email: 'aisyah@selangor-fc.my',
    customer_phone: '+60 17-889 2233',
    print_type: 'sublimation',
    design_id: 'des-2',
    design_title: 'Apex Gradient Football Kit',
    mockup_url: '/images/prod_sportswear.jpg',
    fabric_material_id: 'mat-2',
    fabric_name: 'Drifit Microfiber (Smooth)',
    apparel_cut_id: 'cut-2',
    cut_name: 'Short Sleeve V-Neck Pro',
    sizing_breakdown: { M: 8, L: 10, XL: 4 },
    total_quantity: 20,
    raw_unit_price: 32.00,
    discount_percentage: 5,
    final_unit_price: 30.40,
    total_amount: 608.00,
    status: 'heat_press',
    production_notes: 'Includes sponsor logo on center chest and gold sleeve trim.',
    shipping_address: 'Blok B, Seksyen 7, 40000 Shah Alam, Selangor',
    shipping_courier: 'Pos Laju MY',
    tracking_number: 'ER992019401MY',
    created_at: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 3600 * 1000).toISOString(),
  },
  {
    id: 'ord-1003',
    order_number: 'SFV-2026-003',
    customer_name: 'Danial Haziq',
    customer_email: 'danial@johor-cycling.my',
    customer_phone: '+60 19-332 1100',
    print_type: 'dtf',
    design_id: 'des-3',
    design_title: 'Tokyo Drift Kanji DTF Tee',
    mockup_url: '/images/prod_tshirt.jpg',
    dtf_dimension_id: 'dtf-3',
    dtf_dimension_name: 'A3 Large Statement (30x42 cm)',
    dtf_option_type: 'with_garment',
    garment_blank_color: 'Heavy Black 24s Cotton',
    sizing_breakdown: { M: 15, L: 20, XL: 15 },
    total_quantity: 50,
    raw_unit_price: 32.00,
    discount_percentage: 15,
    final_unit_price: 27.20,
    total_amount: 1360.00,
    status: 'ready_to_ship',
    production_notes: 'Hot peel film, second heat press with silicone sheet for matte finish.',
    shipping_address: 'No 88, Jalan Sutera, 81300 Skudai, Johor',
    shipping_courier: 'Ninja Van MY',
    tracking_number: 'NVMY992018841',
    created_at: new Date(Date.now() - 72 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
  },
];
