import { NextRequest, NextResponse } from 'next/server';

// Malaysia Postcode → Bandar + Negeri mapping
// Source: data.gov.my & Pos Malaysia
// Compact format: [postcode_prefix]: [city, state]
const MALAYSIA_POSTCODE_MAP: Record<string, { city: string; state: string }> = {
  // SELANGOR
  '400': { city: 'Shah Alam', state: 'Selangor' },
  '401': { city: 'Shah Alam', state: 'Selangor' },
  '402': { city: 'Shah Alam', state: 'Selangor' },
  '403': { city: 'Shah Alam', state: 'Selangor' },
  '404': { city: 'Shah Alam', state: 'Selangor' },
  '405': { city: 'Klang', state: 'Selangor' },
  '406': { city: 'Klang', state: 'Selangor' },
  '407': { city: 'Klang', state: 'Selangor' },
  '408': { city: 'Klang', state: 'Selangor' },
  '409': { city: 'Klang', state: 'Selangor' },
  '410': { city: 'Petaling Jaya', state: 'Selangor' },
  '411': { city: 'Petaling Jaya', state: 'Selangor' },
  '412': { city: 'Subang Jaya', state: 'Selangor' },
  '413': { city: 'Subang Jaya', state: 'Selangor' },
  '414': { city: 'Subang Jaya', state: 'Selangor' },
  '415': { city: 'Puchong', state: 'Selangor' },
  '416': { city: 'Puchong', state: 'Selangor' },
  '417': { city: 'Kajang', state: 'Selangor' },
  '418': { city: 'Kajang', state: 'Selangor' },
  '419': { city: 'Semenyih', state: 'Selangor' },
  '420': { city: 'Rawang', state: 'Selangor' },
  '421': { city: 'Rawang', state: 'Selangor' },
  '422': { city: 'Hulu Selangor', state: 'Selangor' },
  '423': { city: 'Bukit Beruntung', state: 'Selangor' },
  '424': { city: 'Batang Kali', state: 'Selangor' },
  '425': { city: 'Kuala Kubu Bharu', state: 'Selangor' },
  '426': { city: 'Ampang', state: 'Selangor' },
  '427': { city: 'Ampang', state: 'Selangor' },
  '428': { city: 'Cheras', state: 'Selangor' },
  '429': { city: 'Cheras', state: 'Selangor' },
  '430': { city: 'Sepang', state: 'Selangor' },
  '431': { city: 'Sepang', state: 'Selangor' },
  '432': { city: 'Dengkil', state: 'Selangor' },
  '433': { city: 'Nilai', state: 'Negeri Sembilan' },
  '434': { city: 'Bangi', state: 'Selangor' },
  '435': { city: 'Bangi', state: 'Selangor' },
  '436': { city: 'Bangi', state: 'Selangor' },
  '437': { city: 'Cyberjaya', state: 'Selangor' },
  '438': { city: 'Putrajaya', state: 'Wilayah Persekutuan Putrajaya' },
  '439': { city: 'Putrajaya', state: 'Wilayah Persekutuan Putrajaya' },
  '440': { city: 'Sabak Bernam', state: 'Selangor' },
  '441': { city: 'Kuala Selangor', state: 'Selangor' },
  '442': { city: 'Kuala Selangor', state: 'Selangor' },
  '443': { city: 'Selayang', state: 'Selangor' },
  '444': { city: 'Selayang', state: 'Selangor' },
  '445': { city: 'Batu Caves', state: 'Selangor' },
  '446': { city: 'Batu Caves', state: 'Selangor' },
  // WILAYAH PERSEKUTUAN KUALA LUMPUR (50xxx - 60xxx)
  '500': { city: 'Kuala Lumpur', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '501': { city: 'Kuala Lumpur', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '502': { city: 'Kuala Lumpur', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '503': { city: 'Kuala Lumpur', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '504': { city: 'Kuala Lumpur', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '505': { city: 'Kuala Lumpur', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '510': { city: 'Sentul', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '511': { city: 'Sentul', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '512': { city: 'Sentul / Segambut', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '520': { city: 'Kepong', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '521': { city: 'Kepong', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '522': { city: 'Kepong / Menjalara', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '530': { city: 'Setapak', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '531': { city: 'Setapak / Melawati', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '532': { city: 'Wangsa Maju', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '533': { city: 'Wangsa Maju', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '540': { city: 'Keramat / Ampang', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '541': { city: 'Keramat', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '542': { city: 'Setiawangsa', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '550': { city: 'Cheras / Pudu', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '551': { city: 'Bukit Bintang / Pudu', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '552': { city: 'Maluri / Cheras', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '560': { city: 'Cheras', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '561': { city: 'Cheras', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '570': { city: 'Bukit Jalil / Sungai Besi', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '571': { city: 'Bandar Tun Razak', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '580': { city: 'Old Klang Road', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '581': { city: 'Kuchai Lama', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '582': { city: 'Taman Desa', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '590': { city: 'Bangsar', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '591': { city: 'Bangsar', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '592': { city: 'Pantai / Bangsar South', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '600': { city: 'TTDI / Damansara', state: 'Wilayah Persekutuan Kuala Lumpur' },
  // PUTRAJAYA & LABUAN
  '620': { city: 'Putrajaya', state: 'Wilayah Persekutuan Putrajaya' },
  '621': { city: 'Putrajaya', state: 'Wilayah Persekutuan Putrajaya' },
  '622': { city: 'Putrajaya', state: 'Wilayah Persekutuan Putrajaya' },
  '623': { city: 'Putrajaya', state: 'Wilayah Persekutuan Putrajaya' },
  '625': { city: 'Putrajaya', state: 'Wilayah Persekutuan Putrajaya' },
  '626': { city: 'Putrajaya', state: 'Wilayah Persekutuan Putrajaya' },
  '629': { city: 'Putrajaya', state: 'Wilayah Persekutuan Putrajaya' },
  '870': { city: 'Labuan', state: 'Wilayah Persekutuan Labuan' },
  // PULAU PINANG
  '100': { city: 'Georgetown', state: 'Pulau Pinang' },
  '101': { city: 'Georgetown', state: 'Pulau Pinang' },
  '102': { city: 'Georgetown', state: 'Pulau Pinang' },
  '103': { city: 'Ayer Itam', state: 'Pulau Pinang' },
  '104': { city: 'Batu Ferringhi', state: 'Pulau Pinang' },
  '105': { city: 'Balik Pulau', state: 'Pulau Pinang' },
  '106': { city: 'Bayan Lepas', state: 'Pulau Pinang' },
  '107': { city: 'Bayan Baru', state: 'Pulau Pinang' },
  '108': { city: 'Gelugor', state: 'Pulau Pinang' },
  '109': { city: 'Georgetown', state: 'Pulau Pinang' },
  '110': { city: 'Butterworth', state: 'Pulau Pinang' },
  '111': { city: 'Butterworth', state: 'Pulau Pinang' },
  '112': { city: 'Butterworth', state: 'Pulau Pinang' },
  '113': { city: 'Penang Hill', state: 'Pulau Pinang' },
  '114': { city: 'Seberang Jaya', state: 'Pulau Pinang' },
  '115': { city: 'Bukit Mertajam', state: 'Pulau Pinang' },
  '116': { city: 'Bukit Mertajam', state: 'Pulau Pinang' },
  '117': { city: 'Simpang Ampat', state: 'Pulau Pinang' },
  '118': { city: 'Nibong Tebal', state: 'Pulau Pinang' },
  '119': { city: 'Kepala Batas', state: 'Pulau Pinang' },
  // JOHOR
  '790': { city: 'Johor Bahru', state: 'Johor' },
  '791': { city: 'Johor Bahru', state: 'Johor' },
  '792': { city: 'Johor Bahru', state: 'Johor' },
  '793': { city: 'Johor Bahru', state: 'Johor' },
  '794': { city: 'Johor Bahru', state: 'Johor' },
  '795': { city: 'Johor Bahru', state: 'Johor' },
  '796': { city: 'Johor Bahru', state: 'Johor' },
  '797': { city: 'Johor Bahru', state: 'Johor' },
  '798': { city: 'Skudai', state: 'Johor' },
  '799': { city: 'Skudai', state: 'Johor' },
  '800': { city: 'Johor Bahru', state: 'Johor' },
  '801': { city: 'Johor Bahru', state: 'Johor' },
  '802': { city: 'Johor Bahru', state: 'Johor' },
  '803': { city: 'Johor Bahru', state: 'Johor' },
  '804': { city: 'Johor Bahru', state: 'Johor' },
  '805': { city: 'Johor Bahru', state: 'Johor' },
  '806': { city: 'Johor Bahru', state: 'Johor' },
  '807': { city: 'Johor Bahru', state: 'Johor' },
  '808': { city: 'Pontian', state: 'Johor' },
  '809': { city: 'Pontian', state: 'Johor' },
  '810': { city: 'Johor Bahru', state: 'Johor' },
  '811': { city: 'Ulu Tiram', state: 'Johor' },
  '812': { city: 'Senai', state: 'Johor' },
  '813': { city: 'Kulai', state: 'Johor' },
  '814': { city: 'Kluang', state: 'Johor' },
  '815': { city: 'Kluang', state: 'Johor' },
  '816': { city: 'Kota Tinggi', state: 'Johor' },
  '817': { city: 'Kota Tinggi', state: 'Johor' },
  '818': { city: 'Mersing', state: 'Johor' },
  '819': { city: 'Mersing', state: 'Johor' },
  '820': { city: 'Segamat', state: 'Johor' },
  '821': { city: 'Segamat', state: 'Johor' },
  '822': { city: 'Muar', state: 'Johor' },
  '823': { city: 'Muar', state: 'Johor' },
  '824': { city: 'Batu Pahat', state: 'Johor' },
  '825': { city: 'Batu Pahat', state: 'Johor' },
  // PERAK
  '300': { city: 'Ipoh', state: 'Perak' },
  '301': { city: 'Ipoh', state: 'Perak' },
  '302': { city: 'Ipoh', state: 'Perak' },
  '303': { city: 'Ipoh', state: 'Perak' },
  '304': { city: 'Ipoh', state: 'Perak' },
  '305': { city: 'Ipoh', state: 'Perak' },
  '306': { city: 'Ipoh', state: 'Perak' },
  '307': { city: 'Ipoh', state: 'Perak' },
  '308': { city: 'Ipoh', state: 'Perak' },
  '309': { city: 'Ipoh', state: 'Perak' },
  '310': { city: 'Taiping', state: 'Perak' },
  '311': { city: 'Taiping', state: 'Perak' },
  '312': { city: 'Taiping', state: 'Perak' },
  '313': { city: 'Teluk Intan', state: 'Perak' },
  '314': { city: 'Teluk Intan', state: 'Perak' },
  '315': { city: 'Sungai Siput', state: 'Perak' },
  '316': { city: 'Kuala Kangsar', state: 'Perak' },
  '317': { city: 'Batu Gajah', state: 'Perak' },
  '318': { city: 'Sitiawan', state: 'Perak' },
  '319': { city: 'Lumut', state: 'Perak' },
  '320': { city: 'Manjung', state: 'Perak' },
  // KEDAH
  '050': { city: 'Alor Setar', state: 'Kedah' },
  '051': { city: 'Alor Setar', state: 'Kedah' },
  '052': { city: 'Alor Setar', state: 'Kedah' },
  '053': { city: 'Alor Setar', state: 'Kedah' },
  '054': { city: 'Jitra', state: 'Kedah' },
  '055': { city: 'Changlun', state: 'Kedah' },
  '056': { city: 'Kuala Nerang', state: 'Kedah' },
  '057': { city: 'Pendang', state: 'Kedah' },
  '058': { city: 'Yan', state: 'Kedah' },
  '059': { city: 'Sungai Petani', state: 'Kedah' },
  '060': { city: 'Sungai Petani', state: 'Kedah' },
  '061': { city: 'Sungai Petani', state: 'Kedah' },
  '062': { city: 'Bedong', state: 'Kedah' },
  '063': { city: 'Gurun', state: 'Kedah' },
  '064': { city: 'Baling', state: 'Kedah' },
  '065': { city: 'Kulim', state: 'Kedah' },
  '066': { city: 'Langkawi', state: 'Kedah' },
  // KELANTAN
  '150': { city: 'Kota Bharu', state: 'Kelantan' },
  '151': { city: 'Kota Bharu', state: 'Kelantan' },
  '152': { city: 'Kota Bharu', state: 'Kelantan' },
  '153': { city: 'Kota Bharu', state: 'Kelantan' },
  '154': { city: 'Pasir Mas', state: 'Kelantan' },
  '155': { city: 'Tumpat', state: 'Kelantan' },
  '156': { city: 'Pasir Puteh', state: 'Kelantan' },
  '157': { city: 'Tanah Merah', state: 'Kelantan' },
  '158': { city: 'Machang', state: 'Kelantan' },
  '159': { city: 'Kuala Krai', state: 'Kelantan' },
  '160': { city: 'Gua Musang', state: 'Kelantan' },
  // TERENGGANU
  '200': { city: 'Kuala Terengganu', state: 'Terengganu' },
  '201': { city: 'Kuala Terengganu', state: 'Terengganu' },
  '202': { city: 'Kuala Terengganu', state: 'Terengganu' },
  '203': { city: 'Kuala Terengganu', state: 'Terengganu' },
  '204': { city: 'Kuala Terengganu', state: 'Terengganu' },
  '205': { city: 'Kuala Terengganu', state: 'Terengganu' },
  '206': { city: 'Marang', state: 'Terengganu' },
  '207': { city: 'Dungun', state: 'Terengganu' },
  '208': { city: 'Kemaman', state: 'Terengganu' },
  '209': { city: 'Besut', state: 'Terengganu' },
  // PAHANG
  '250': { city: 'Kuantan', state: 'Pahang' },
  '251': { city: 'Kuantan', state: 'Pahang' },
  '252': { city: 'Kuantan', state: 'Pahang' },
  '253': { city: 'Kuantan', state: 'Pahang' },
  '254': { city: 'Maran', state: 'Pahang' },
  '255': { city: 'Temerloh', state: 'Pahang' },
  '256': { city: 'Bentong', state: 'Pahang' },
  '257': { city: 'Raub', state: 'Pahang' },
  '258': { city: 'Cameron Highlands', state: 'Pahang' },
  '259': { city: 'Jerantut', state: 'Pahang' },
  // NEGERI SEMBILAN
  '700': { city: 'Seremban', state: 'Negeri Sembilan' },
  '701': { city: 'Seremban', state: 'Negeri Sembilan' },
  '702': { city: 'Seremban', state: 'Negeri Sembilan' },
  '703': { city: 'Seremban', state: 'Negeri Sembilan' },
  '704': { city: 'Nilai', state: 'Negeri Sembilan' },
  '705': { city: 'Port Dickson', state: 'Negeri Sembilan' },
  '706': { city: 'Rembau', state: 'Negeri Sembilan' },
  '707': { city: 'Tampin', state: 'Negeri Sembilan' },
  '708': { city: 'Jelebu', state: 'Negeri Sembilan' },
  // MELAKA
  '750': { city: 'Melaka', state: 'Melaka' },
  '751': { city: 'Melaka', state: 'Melaka' },
  '752': { city: 'Melaka', state: 'Melaka' },
  '753': { city: 'Melaka', state: 'Melaka' },
  '754': { city: 'Melaka', state: 'Melaka' },
  '755': { city: 'Melaka', state: 'Melaka' },
  '756': { city: 'Alor Gajah', state: 'Melaka' },
  '757': { city: 'Jasin', state: 'Melaka' },
  '758': { city: 'Merlimau', state: 'Melaka' },
  // PERLIS
  '010': { city: 'Kangar', state: 'Perlis' },
  '011': { city: 'Kangar', state: 'Perlis' },
  '012': { city: 'Arau', state: 'Perlis' },
  '013': { city: 'Padang Besar', state: 'Perlis' },
  // SABAH
  '880': { city: 'Kota Kinabalu', state: 'Sabah' },
  '881': { city: 'Kota Kinabalu', state: 'Sabah' },
  '882': { city: 'Kota Kinabalu', state: 'Sabah' },
  '883': { city: 'Kota Kinabalu', state: 'Sabah' },
  '884': { city: 'Kota Kinabalu', state: 'Sabah' },
  '885': { city: 'Kota Kinabalu', state: 'Sabah' },
  '886': { city: 'Kota Kinabalu', state: 'Sabah' },
  '887': { city: 'Tuaran', state: 'Sabah' },
  '888': { city: 'Ranau', state: 'Sabah' },
  '889': { city: 'Keningau', state: 'Sabah' },
  '890': { city: 'Sandakan', state: 'Sabah' },
  '891': { city: 'Sandakan', state: 'Sabah' },
  '892': { city: 'Tawau', state: 'Sabah' },
  '893': { city: 'Tawau', state: 'Sabah' },
  '894': { city: 'Lahad Datu', state: 'Sabah' },
  '895': { city: 'Semporna', state: 'Sabah' },
  '896': { city: 'Kunak', state: 'Sabah' },
  '897': { city: 'Beaufort', state: 'Sabah' },
  '898': { city: 'Papar', state: 'Sabah' },
  // SARAWAK
  '930': { city: 'Kuching', state: 'Sarawak' },
  '931': { city: 'Kuching', state: 'Sarawak' },
  '932': { city: 'Kuching', state: 'Sarawak' },
  '933': { city: 'Kuching', state: 'Sarawak' },
  '934': { city: 'Kuching', state: 'Sarawak' },
  '935': { city: 'Serian', state: 'Sarawak' },
  '936': { city: 'Sri Aman', state: 'Sarawak' },
  '940': { city: 'Sibu', state: 'Sarawak' },
  '941': { city: 'Sibu', state: 'Sarawak' },
  '942': { city: 'Sarikei', state: 'Sarawak' },
  '950': { city: 'Miri', state: 'Sarawak' },
  '951': { city: 'Miri', state: 'Sarawak' },
  '952': { city: 'Bintulu', state: 'Sarawak' },
  '960': { city: 'Limbang', state: 'Sarawak' },
  '970': { city: 'Kota Samarahan', state: 'Sarawak' },
};

const MALAYSIA_STATES = [
  'Johor', 'Kedah', 'Kelantan', 'Melaka', 'Negeri Sembilan',
  'Pahang', 'Perak', 'Perlis', 'Pulau Pinang', 'Sabah', 'Sarawak',
  'Selangor', 'Terengganu',
  'Wilayah Persekutuan Kuala Lumpur',
  'Wilayah Persekutuan Labuan',
  'Wilayah Persekutuan Putrajaya',
];

export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url);
  const code = searchParams.get('code')?.trim();

  if (!code || code.length < 3 || code.length > 5) {
    return NextResponse.json(
      { success: false, message: 'Poskod mesti antara 3-5 digit.' },
      { status: 400 }
    );
  }

  // Try exact 5-digit match first, then prefix-based lookup
  const prefix3 = code.slice(0, 3);

  const result = MALAYSIA_POSTCODE_MAP[prefix3];

  if (!result) {
    return NextResponse.json(
      { success: false, message: 'Poskod tidak dijumpai dalam senarai Malaysia.' },
      { status: 404 }
    );
  }

  return NextResponse.json({
    success: true,
    postcode: code,
    city: result.city,
    state: result.state,
  });
}
