import { NextRequest, NextResponse } from 'next/server';

// Comprehensive Malaysia Postcode Mapping (3-digit prefix lookup + 2-digit state fallback)
// Sources: Pos Malaysia Official Directory & data.gov.my
const MALAYSIA_POSTCODE_MAP: Record<string, { city: string; state: string }> = {
  // PERLIS (01xxx - 02xxx)
  '010': { city: 'Kangar', state: 'Perlis' },
  '015': { city: 'Kangar', state: 'Perlis' },
  '020': { city: 'Kuala Perlis', state: 'Perlis' },
  '021': { city: 'Padang Besar', state: 'Perlis' },
  '022': { city: 'Kaki Bukit', state: 'Perlis' },
  '024': { city: 'Kangar', state: 'Perlis' },
  '025': { city: 'Kabi Bukit', state: 'Perlis' },
  '026': { city: 'Arau', state: 'Perlis' },
  '027': { city: 'Simpang Empat', state: 'Perlis' },
  '028': { city: 'Simpang Empat', state: 'Perlis' },

  // KEDAH (05xxx - 09xxx)
  '050': { city: 'Alor Setar', state: 'Kedah' },
  '051': { city: 'Alor Setar', state: 'Kedah' },
  '052': { city: 'Alor Setar', state: 'Kedah' },
  '053': { city: 'Alor Setar', state: 'Kedah' },
  '054': { city: 'Alor Setar', state: 'Kedah' },
  '055': { city: 'Alor Setar', state: 'Kedah' },
  '056': { city: 'Kuala Nerang', state: 'Kedah' },
  '057': { city: 'Pendang', state: 'Kedah' },
  '058': { city: 'Yan', state: 'Kedah' },
  '059': { city: 'Alor Setar', state: 'Kedah' },
  '060': { city: 'Jitra', state: 'Kedah' },
  '061': { city: 'Kodiang / Changlun', state: 'Kedah' },
  '062': { city: 'Kepala Batas', state: 'Kedah' },
  '063': { city: 'Kuala Nerang', state: 'Kedah' },
  '064': { city: 'Pokok Sena', state: 'Kedah' },
  '065': { city: 'Langgar', state: 'Kedah' },
  '066': { city: 'Kuala Kedah', state: 'Kedah' },
  '067': { city: 'Pendang', state: 'Kedah' },
  '068': { city: 'Sik', state: 'Kedah' },
  '069': { city: 'Yan', state: 'Kedah' },
  '070': { city: 'Langkawi', state: 'Kedah' },
  '071': { city: 'Langkawi', state: 'Kedah' },
  '080': { city: 'Sungai Petani', state: 'Kedah' },
  '081': { city: 'Bedong', state: 'Kedah' },
  '082': { city: 'Sik', state: 'Kedah' },
  '083': { city: 'Gurun', state: 'Kedah' },
  '084': { city: 'Merbok', state: 'Kedah' },
  '085': { city: 'Kota Kuala Muda', state: 'Kedah' },
  '086': { city: 'Tikam Batu', state: 'Kedah' },
  '087': { city: 'Jeniang', state: 'Kedah' },
  '088': { city: 'Gurun', state: 'Kedah' },
  '090': { city: 'Kulim', state: 'Kedah' },
  '091': { city: 'Baling', state: 'Kedah' },
  '092': { city: 'Kupang', state: 'Kedah' },
  '093': { city: 'Kuala Ketil', state: 'Kedah' },
  '094': { city: 'Padang Serai', state: 'Kedah' },
  '095': { city: 'Lunas', state: 'Kedah' },
  '096': { city: 'Lunas', state: 'Kedah' },
  '097': { city: 'Karangan', state: 'Kedah' },
  '098': { city: 'Serdang / Bandar Baharu', state: 'Kedah' },

  // PULAU PINANG (10xxx - 14xxx)
  '100': { city: 'Georgetown', state: 'Pulau Pinang' },
  '101': { city: 'Georgetown', state: 'Pulau Pinang' },
  '102': { city: 'Georgetown', state: 'Pulau Pinang' },
  '103': { city: 'Georgetown', state: 'Pulau Pinang' },
  '104': { city: 'Georgetown', state: 'Pulau Pinang' },
  '105': { city: 'Georgetown', state: 'Pulau Pinang' },
  '106': { city: 'Georgetown', state: 'Pulau Pinang' },
  '107': { city: 'Georgetown', state: 'Pulau Pinang' },
  '108': { city: 'Georgetown', state: 'Pulau Pinang' },
  '109': { city: 'Georgetown', state: 'Pulau Pinang' },
  '110': { city: 'Batu Ferringhi / Teluk Bahang', state: 'Pulau Pinang' },
  '111': { city: 'Batu Ferringhi', state: 'Pulau Pinang' },
  '112': { city: 'Tanjung Bungah', state: 'Pulau Pinang' },
  '113': { city: 'Penang Hill', state: 'Pulau Pinang' },
  '114': { city: 'Ayer Itam', state: 'Pulau Pinang' },
  '115': { city: 'Ayer Itam', state: 'Pulau Pinang' },
  '116': { city: 'Jelutong', state: 'Pulau Pinang' },
  '117': { city: 'Gelugor', state: 'Pulau Pinang' },
  '118': { city: 'USM Gelugor', state: 'Pulau Pinang' },
  '119': { city: 'Bayan Lepas / Bayan Baru', state: 'Pulau Pinang' },
  '120': { city: 'Butterworth', state: 'Pulau Pinang' },
  '121': { city: 'Butterworth', state: 'Pulau Pinang' },
  '122': { city: 'Butterworth', state: 'Pulau Pinang' },
  '123': { city: 'Butterworth', state: 'Pulau Pinang' },
  '130': { city: 'Sungai Dua', state: 'Pulau Pinang' },
  '131': { city: 'Penaga', state: 'Pulau Pinang' },
  '132': { city: 'Kepala Batas', state: 'Pulau Pinang' },
  '133': { city: 'Tasek Gelugor', state: 'Pulau Pinang' },
  '134': { city: 'Butterworth', state: 'Pulau Pinang' },
  '135': { city: 'Permatang Pauh', state: 'Pulau Pinang' },
  '136': { city: 'Perai', state: 'Pulau Pinang' },
  '137': { city: 'Seberang Jaya / Perai', state: 'Pulau Pinang' },
  '138': { city: 'Butterworth', state: 'Pulau Pinang' },
  '140': { city: 'Bukit Mertajam', state: 'Pulau Pinang' },
  '141': { city: 'Simpang Ampat', state: 'Pulau Pinang' },
  '142': { city: 'Sungai Bakap', state: 'Pulau Pinang' },
  '143': { city: 'Nibong Tebal', state: 'Pulau Pinang' },
  '144': { city: 'Kubang Semang', state: 'Pulau Pinang' },

  // KELANTAN (15xxx - 18xxx)
  '150': { city: 'Kota Bharu', state: 'Kelantan' },
  '151': { city: 'Kota Bharu', state: 'Kelantan' },
  '152': { city: 'Kota Bharu', state: 'Kelantan' },
  '153': { city: 'Kota Bharu', state: 'Kelantan' },
  '154': { city: 'Kota Bharu', state: 'Kelantan' },
  '160': { city: 'Bachok', state: 'Kelantan' },
  '161': { city: 'Kota Bharu', state: 'Kelantan' },
  '162': { city: 'Tumpat', state: 'Kelantan' },
  '163': { city: 'Bachok', state: 'Kelantan' },
  '164': { city: 'Melor / Ketereh', state: 'Kelantan' },
  '165': { city: 'Wakaf Bharu', state: 'Kelantan' },
  '166': { city: 'Pulau Chondong', state: 'Kelantan' },
  '167': { city: 'Cherang Ruku', state: 'Kelantan' },
  '168': { city: 'Pasir Puteh', state: 'Kelantan' },
  '170': { city: 'Pasir Mas', state: 'Kelantan' },
  '172': { city: 'Rantau Panjang', state: 'Kelantan' },
  '175': { city: 'Tanah Merah', state: 'Kelantan' },
  '176': { city: 'Jeli', state: 'Kelantan' },
  '177': { city: 'Ayer Lanas', state: 'Kelantan' },
  '180': { city: 'Kuala Krai', state: 'Kelantan' },
  '182': { city: 'Dabong', state: 'Kelantan' },
  '183': { city: 'Gua Musang', state: 'Kelantan' },
  '184': { city: 'Temangan', state: 'Kelantan' },
  '185': { city: 'Machang', state: 'Kelantan' },

  // TERENGGANU (20xxx - 24xxx)
  '200': { city: 'Kuala Terengganu', state: 'Terengganu' },
  '201': { city: 'Kuala Terengganu', state: 'Terengganu' },
  '202': { city: 'Kuala Terengganu', state: 'Terengganu' },
  '203': { city: 'Kuala Terengganu', state: 'Terengganu' },
  '204': { city: 'Kuala Terengganu', state: 'Terengganu' },
  '205': { city: 'Kuala Terengganu', state: 'Terengganu' },
  '210': { city: 'Kuala Nerus / Kuala Terengganu', state: 'Terengganu' },
  '211': { city: 'Kuala Terengganu', state: 'Terengganu' },
  '212': { city: 'Kuala Terengganu', state: 'Terengganu' },
  '213': { city: 'Kuala Terengganu', state: 'Terengganu' },
  '214': { city: 'Bukit Payong', state: 'Terengganu' },
  '215': { city: 'Sungai Tong', state: 'Terengganu' },
  '216': { city: 'Marang', state: 'Terengganu' },
  '217': { city: 'Kuala Berang', state: 'Terengganu' },
  '218': { city: 'Ajil', state: 'Terengganu' },
  '220': { city: 'Jerteh', state: 'Terengganu' },
  '221': { city: 'Permaisuri', state: 'Terengganu' },
  '222': { city: 'Kampung Raja', state: 'Terengganu' },
  '223': { city: 'Kuala Besut', state: 'Terengganu' },
  '230': { city: 'Dungun', state: 'Terengganu' },
  '231': { city: 'Paka', state: 'Terengganu' },
  '232': { city: 'Bukit Besi', state: 'Terengganu' },
  '233': { city: 'Ketengah Jaya', state: 'Terengganu' },
  '234': { city: 'Al Muktatfi Billah Shah', state: 'Terengganu' },
  '240': { city: 'Chukai / Kemaman', state: 'Terengganu' },
  '241': { city: 'Kijal', state: 'Terengganu' },
  '242': { city: 'Kemasek', state: 'Terengganu' },
  '243': { city: 'Kerteh', state: 'Terengganu' },

  // PAHANG (25xxx - 28xxx, 39xxx, 49xxx, 69xxx)
  '250': { city: 'Kuantan', state: 'Pahang' },
  '251': { city: 'Kuantan', state: 'Pahang' },
  '252': { city: 'Kuantan', state: 'Pahang' },
  '253': { city: 'Kuantan', state: 'Pahang' },
  '260': { city: 'Gambang', state: 'Pahang' },
  '261': { city: 'Balok', state: 'Pahang' },
  '262': { city: 'Sungai Lembing', state: 'Pahang' },
  '263': { city: 'Maran', state: 'Pahang' },
  '264': { city: 'Bandar Pusat Jengka', state: 'Pahang' },
  '265': { city: 'Maran', state: 'Pahang' },
  '266': { city: 'Pekan', state: 'Pahang' },
  '267': { city: 'Muadzam Shah', state: 'Pahang' },
  '268': { city: 'Kuala Rompin', state: 'Pahang' },
  '269': { city: 'Bandar Tun Abdul Razak', state: 'Pahang' },
  '270': { city: 'Jerantut', state: 'Pahang' },
  '271': { city: 'Kuala Krau', state: 'Pahang' },
  '272': { city: 'Kuala Lipis', state: 'Pahang' },
  '273': { city: 'Padang Tengku', state: 'Pahang' },
  '274': { city: 'Benta', state: 'Pahang' },
  '275': { city: 'Benta', state: 'Pahang' },
  '276': { city: 'Raub', state: 'Pahang' },
  '280': { city: 'Temerloh', state: 'Pahang' },
  '281': { city: 'Chenor', state: 'Pahang' },
  '282': { city: 'Mengkarak', state: 'Pahang' },
  '283': { city: 'Triang', state: 'Pahang' },
  '284': { city: 'Mentakab', state: 'Pahang' },
  '285': { city: 'Lanchang', state: 'Pahang' },
  '286': { city: 'Karak', state: 'Pahang' },
  '287': { city: 'Bentong', state: 'Pahang' },
  '288': { city: 'Lurah Bilut', state: 'Pahang' },
  '390': { city: 'Tanah Rata', state: 'Pahang' },
  '391': { city: 'Brinchang', state: 'Pahang' },
  '392': { city: 'Ringlet', state: 'Pahang' },
  '490': { city: 'Bukit Fraser', state: 'Pahang' },
  '690': { city: 'Genting Highlands', state: 'Pahang' },

  // PERAK (30xxx - 36xxx)
  '300': { city: 'Ipoh', state: 'Perak' },
  '301': { city: 'Ipoh', state: 'Perak' },
  '302': { city: 'Ipoh', state: 'Perak' },
  '303': { city: 'Ipoh', state: 'Perak' },
  '304': { city: 'Ipoh', state: 'Perak' },
  '310': { city: 'Batu Gajah', state: 'Perak' },
  '311': { city: 'Sungkai / Gopeng', state: 'Perak' },
  '312': { city: 'Chemor', state: 'Perak' },
  '313': { city: 'Ipoh / Simpang Pulai', state: 'Perak' },
  '314': { city: 'Ipoh', state: 'Perak' },
  '315': { city: 'Lahat', state: 'Perak' },
  '316': { city: 'Gopeng', state: 'Perak' },
  '317': { city: 'Malim Nawar', state: 'Perak' },
  '318': { city: 'Tanjung Tualang', state: 'Perak' },
  '319': { city: 'Kampar', state: 'Perak' },
  '320': { city: 'Sitiawan', state: 'Perak' },
  '321': { city: 'Pangkor', state: 'Perak' },
  '322': { city: 'Lumut', state: 'Perak' },
  '323': { city: 'Segari', state: 'Perak' },
  '324': { city: 'Ayer Tawar', state: 'Perak' },
  '325': { city: 'Changkat Jering', state: 'Perak' },
  '326': { city: 'Bota', state: 'Perak' },
  '327': { city: 'Beruas', state: 'Perak' },
  '328': { city: 'Parit', state: 'Perak' },
  '330': { city: 'Kuala Kangsar', state: 'Perak' },
  '331': { city: 'Pengkalan Hulu', state: 'Perak' },
  '332': { city: 'Intan', state: 'Perak' },
  '333': { city: 'Gerik', state: 'Perak' },
  '334': { city: 'Lenggong', state: 'Perak' },
  '336': { city: 'Enggor', state: 'Perak' },
  '337': { city: 'Padang Rengas', state: 'Perak' },
  '338': { city: 'Manong', state: 'Perak' },
  '340': { city: 'Taiping', state: 'Perak' },
  '341': { city: 'Selama', state: 'Perak' },
  '342': { city: 'Parit Buntar', state: 'Perak' },
  '343': { city: 'Bagan Serai', state: 'Perak' },
  '344': { city: 'Semanggol', state: 'Perak' },
  '345': { city: 'Batu Kurau', state: 'Perak' },
  '346': { city: 'Kamunting', state: 'Perak' },
  '347': { city: 'Simpang', state: 'Perak' },
  '348': { city: 'Trong', state: 'Perak' },
  '349': { city: 'Pantai Remis', state: 'Perak' },
  '350': { city: 'Tapah', state: 'Perak' },
  '353': { city: 'Chenderiang', state: 'Perak' },
  '354': { city: 'Temoh', state: 'Perak' },
  '355': { city: 'Bidor', state: 'Perak' },
  '356': { city: 'Sungkai', state: 'Perak' },
  '357': { city: 'Trolak', state: 'Perak' },
  '358': { city: 'Slim River', state: 'Perak' },
  '359': { city: 'Tanjung Malim', state: 'Perak' },
  '360': { city: 'Teluk Intan', state: 'Perak' },
  '361': { city: 'Selekoh', state: 'Perak' },
  '362': { city: 'Selekoh', state: 'Perak' },
  '363': { city: 'Sungai Sumun', state: 'Perak' },
  '364': { city: 'Hutan Melintang', state: 'Perak' },
  '365': { city: 'Bagan Datuk', state: 'Perak' },
  '366': { city: 'Chenderong Balai', state: 'Perak' },
  '367': { city: 'Langkap', state: 'Perak' },
  '368': { city: 'Kampung Gajah', state: 'Perak' },

  // SELANGOR (40xxx - 48xxx)
  '400': { city: 'Shah Alam', state: 'Selangor' },
  '401': { city: 'Shah Alam', state: 'Selangor' },
  '402': { city: 'Shah Alam', state: 'Selangor' },
  '403': { city: 'Shah Alam', state: 'Selangor' },
  '404': { city: 'Shah Alam', state: 'Selangor' },
  '405': { city: 'Klang', state: 'Selangor' },
  '406': { city: 'Klang', state: 'Selangor' },
  '407': { city: 'Klang', state: 'Selangor' },
  '408': { city: 'Klang', state: 'Selangor' },
  '409': { city: 'Klang', state: 'Selangor' },
  '410': { city: 'Klang', state: 'Selangor' },
  '411': { city: 'Klang', state: 'Selangor' },
  '412': { city: 'Klang', state: 'Selangor' },
  '413': { city: 'Klang', state: 'Selangor' },
  '414': { city: 'Klang', state: 'Selangor' },
  '420': { city: 'Pelabuhan Klang', state: 'Selangor' },
  '421': { city: 'Klang', state: 'Selangor' },
  '422': { city: 'Kapar', state: 'Selangor' },
  '423': { city: 'Puncak Alam / Bandar Puncak Alam', state: 'Selangor' },
  '424': { city: 'Meru', state: 'Selangor' },
  '425': { city: 'Telok Panglima Garang', state: 'Selangor' },
  '426': { city: 'Jenjarom', state: 'Selangor' },
  '427': { city: 'Banting', state: 'Selangor' },
  '428': { city: 'Tanjong Sepat', state: 'Selangor' },
  '429': { city: 'Pulau Indah', state: 'Selangor' },
  '430': { city: 'Kajang', state: 'Selangor' },
  '431': { city: 'Hulu Langat', state: 'Selangor' },
  '432': { city: 'Cheras', state: 'Selangor' },
  '433': { city: 'Seri Kembangan / Balakong', state: 'Selangor' },
  '434': { city: 'Serdang', state: 'Selangor' },
  '435': { city: 'Semenyih', state: 'Selangor' },
  '436': { city: 'Bandar Baru Bangi', state: 'Selangor' },
  '437': { city: 'Beranang', state: 'Selangor' },
  '438': { city: 'Dengkil', state: 'Selangor' },
  '439': { city: 'Sepang', state: 'Selangor' },
  '440': { city: 'Kuala Kubu Bharu', state: 'Selangor' },
  '441': { city: 'Kerling', state: 'Selangor' },
  '442': { city: 'Rasa', state: 'Selangor' },
  '443': { city: 'Batang Kali', state: 'Selangor' },
  '450': { city: 'Kuala Selangor', state: 'Selangor' },
  '451': { city: 'Sungai Besar', state: 'Selangor' },
  '452': { city: 'Sabak Bernam', state: 'Selangor' },
  '453': { city: 'Sungai Pelek', state: 'Selangor' },
  '454': { city: 'Sekinchan', state: 'Selangor' },
  '455': { city: 'Tanjong Karang', state: 'Selangor' },
  '456': { city: 'Bestari Jaya', state: 'Selangor' },
  '457': { city: 'Bukit Rotan', state: 'Selangor' },
  '458': { city: 'Jeram', state: 'Selangor' },
  '460': { city: 'Petaling Jaya', state: 'Selangor' },
  '461': { city: 'Petaling Jaya', state: 'Selangor' },
  '462': { city: 'Petaling Jaya', state: 'Selangor' },
  '463': { city: 'Petaling Jaya', state: 'Selangor' },
  '464': { city: 'Petaling Jaya', state: 'Selangor' },
  '465': { city: 'Petaling Jaya', state: 'Selangor' },
  '466': { city: 'Petaling Jaya', state: 'Selangor' },
  '467': { city: 'Petaling Jaya', state: 'Selangor' },
  '468': { city: 'Petaling Jaya', state: 'Selangor' },
  '469': { city: 'Subang Jaya', state: 'Selangor' },
  '470': { city: 'Sungai Buloh', state: 'Selangor' },
  '471': { city: 'Puchong', state: 'Selangor' },
  '472': { city: 'Subang', state: 'Selangor' },
  '473': { city: 'Petaling Jaya / Ara Damansara', state: 'Selangor' },
  '474': { city: 'Petaling Jaya / Damansara', state: 'Selangor' },
  '475': { city: 'Subang Jaya', state: 'Selangor' },
  '476': { city: 'Subang Jaya / USJ', state: 'Selangor' },
  '478': { city: 'Petaling Jaya / Kota Damansara', state: 'Selangor' },
  '480': { city: 'Rawang', state: 'Selangor' },
  '481': { city: 'Batu Arang', state: 'Selangor' },
  '482': { city: 'Serendah', state: 'Selangor' },
  '483': { city: 'Rawang / Bukit Beruntung', state: 'Selangor' },

  // WILAYAH PERSEKUTUAN KUALA LUMPUR (50xxx - 60xxx)
  '500': { city: 'Kuala Lumpur', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '501': { city: 'Kuala Lumpur', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '502': { city: 'Kuala Lumpur', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '503': { city: 'Kuala Lumpur', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '504': { city: 'Kuala Lumpur', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '505': { city: 'Kuala Lumpur', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '506': { city: 'Kuala Lumpur', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '510': { city: 'Sentul', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '511': { city: 'Sentul', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '512': { city: 'Sentul / Segambut', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '520': { city: 'Kepong', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '521': { city: 'Kepong', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '522': { city: 'Bandar Menjalara / Kepong', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '530': { city: 'Setapak', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '531': { city: 'Setapak / Melawati', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '532': { city: 'Wangsa Maju', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '533': { city: 'Setapak', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '540': { city: 'Keramat / Ampang', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '541': { city: 'Keramat', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '542': { city: 'Setiawangsa', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '550': { city: 'Kuala Lumpur / Pudu', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '551': { city: 'Kuala Lumpur / Bukit Bintang', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '552': { city: 'Kuala Lumpur / Cheras', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '553': { city: 'Cheras', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '560': { city: 'Cheras', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '561': { city: 'Cheras', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '570': { city: 'Bukit Jalil / Sungai Besi', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '571': { city: 'Bandar Tun Razak', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '580': { city: 'Kuchai Lama / Old Klang Road', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '581': { city: 'Kuchai Lama', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '582': { city: 'Taman Desa', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '590': { city: 'Bangsar', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '591': { city: 'Bangsar', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '592': { city: 'Bangsar South / Pantai', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '600': { city: 'Taman Tun Dr Ismail / Damansara', state: 'Wilayah Persekutuan Kuala Lumpur' },

  // PUTRAJAYA (62xxx)
  '620': { city: 'Putrajaya', state: 'Wilayah Persekutuan Putrajaya' },
  '621': { city: 'Putrajaya', state: 'Wilayah Persekutuan Putrajaya' },
  '622': { city: 'Putrajaya', state: 'Wilayah Persekutuan Putrajaya' },
  '623': { city: 'Putrajaya', state: 'Wilayah Persekutuan Putrajaya' },
  '625': { city: 'Putrajaya', state: 'Wilayah Persekutuan Putrajaya' },
  '626': { city: 'Putrajaya', state: 'Wilayah Persekutuan Putrajaya' },
  '629': { city: 'Putrajaya', state: 'Wilayah Persekutuan Putrajaya' },

  // CYBERJAYA (63xxx)
  '630': { city: 'Cyberjaya', state: 'Selangor' },
  '631': { city: 'Cyberjaya', state: 'Selangor' },
  '632': { city: 'Cyberjaya', state: 'Selangor' },
  '633': { city: 'Cyberjaya', state: 'Selangor' },

  // NEGERI SEMBILAN (70xxx - 73xxx)
  '700': { city: 'Seremban', state: 'Negeri Sembilan' },
  '701': { city: 'Seremban', state: 'Negeri Sembilan' },
  '702': { city: 'Seremban', state: 'Negeri Sembilan' },
  '703': { city: 'Seremban 2', state: 'Negeri Sembilan' },
  '704': { city: 'Senawang / Seremban', state: 'Negeri Sembilan' },
  '710': { city: 'Port Dickson', state: 'Negeri Sembilan' },
  '711': { city: 'Siliau', state: 'Negeri Sembilan' },
  '712': { city: 'Rantau', state: 'Negeri Sembilan' },
  '713': { city: 'Rembau', state: 'Negeri Sembilan' },
  '714': { city: 'Pedas', state: 'Negeri Sembilan' },
  '715': { city: 'Tanjong Ipoh', state: 'Negeri Sembilan' },
  '716': { city: 'Kuala Klawang', state: 'Negeri Sembilan' },
  '717': { city: 'Mantin', state: 'Negeri Sembilan' },
  '718': { city: 'Nilai', state: 'Negeri Sembilan' },
  '719': { city: 'Labu / Bandar Enstek', state: 'Negeri Sembilan' },
  '720': { city: 'Kuala Pilah', state: 'Negeri Sembilan' },
  '721': { city: 'Bahau', state: 'Negeri Sembilan' },
  '722': { city: 'Batu Kikir', state: 'Negeri Sembilan' },
  '723': { city: 'Simpang Pertang', state: 'Negeri Sembilan' },
  '724': { city: 'Simpang Durian', state: 'Negeri Sembilan' },
  '725': { city: 'Juasseh', state: 'Negeri Sembilan' },
  '730': { city: 'Tampin', state: 'Negeri Sembilan' },
  '731': { city: 'Johol', state: 'Negeri Sembilan' },
  '732': { city: 'Gemencheh', state: 'Negeri Sembilan' },
  '733': { city: 'Batang Melaka', state: 'Negeri Sembilan' },
  '734': { city: 'Gemas', state: 'Negeri Sembilan' },
  '735': { city: 'Rompin', state: 'Negeri Sembilan' },

  // MELAKA (75xxx - 78xxx)
  '750': { city: 'Melaka', state: 'Melaka' },
  '751': { city: 'Melaka', state: 'Melaka' },
  '752': { city: 'Melaka', state: 'Melaka' },
  '753': { city: 'Melaka', state: 'Melaka' },
  '754': { city: 'Ayer Keroh / Melaka', state: 'Melaka' },
  '761': { city: 'Durian Tunggal', state: 'Melaka' },
  '762': { city: 'Kem Trendak', state: 'Melaka' },
  '763': { city: 'Sungai Udang', state: 'Melaka' },
  '764': { city: 'Tanjong Kling', state: 'Melaka' },
  '770': { city: 'Jasin', state: 'Melaka' },
  '771': { city: 'Asahan', state: 'Melaka' },
  '772': { city: 'Bemban', state: 'Melaka' },
  '773': { city: 'Merlimau', state: 'Melaka' },
  '774': { city: 'Sungai Rambai', state: 'Melaka' },
  '775': { city: 'Selandar', state: 'Melaka' },
  '780': { city: 'Alor Gajah', state: 'Melaka' },
  '781': { city: 'Lubok China', state: 'Melaka' },
  '782': { city: 'Kuala Sungai Baru', state: 'Melaka' },
  '783': { city: 'Masjid Tanah', state: 'Melaka' },

  // JOHOR (79xxx - 86xxx)
  '790': { city: 'Iskandar Puteri', state: 'Johor' },
  '791': { city: 'Iskandar Puteri / Nusajaya', state: 'Johor' },
  '792': { city: 'Iskandar Puteri', state: 'Johor' },
  '795': { city: 'Gelang Patah', state: 'Johor' },
  '800': { city: 'Johor Bahru', state: 'Johor' },
  '801': { city: 'Johor Bahru', state: 'Johor' },
  '802': { city: 'Johor Bahru', state: 'Johor' },
  '803': { city: 'Johor Bahru', state: 'Johor' },
  '804': { city: 'Johor Bahru', state: 'Johor' },
  '805': { city: 'Johor Bahru', state: 'Johor' },
  '811': { city: 'Johor Bahru / Mount Austin', state: 'Johor' },
  '812': { city: 'Johor Bahru / Tampoi', state: 'Johor' },
  '813': { city: 'Skudai', state: 'Johor' },
  '814': { city: 'Senai', state: 'Johor' },
  '815': { city: 'Pekan Nanas', state: 'Johor' },
  '816': { city: 'Gelang Patah', state: 'Johor' },
  '817': { city: 'Pasir Gudang', state: 'Johor' },
  '818': { city: 'Ulu Tiram', state: 'Johor' },
  '819': { city: 'Kota Tinggi', state: 'Johor' },
  '820': { city: 'Pontian', state: 'Johor' },
  '821': { city: 'Ayer Baloi', state: 'Johor' },
  '822': { city: 'Benut', state: 'Johor' },
  '823': { city: 'Kukup', state: 'Johor' },
  '830': { city: 'Batu Pahat', state: 'Johor' },
  '831': { city: 'Rengit', state: 'Johor' },
  '832': { city: 'Senggarang', state: 'Johor' },
  '833': { city: 'Sri Gading', state: 'Johor' },
  '834': { city: 'Semerah', state: 'Johor' },
  '835': { city: 'Parit Sulong', state: 'Johor' },
  '836': { city: 'Semerah', state: 'Johor' },
  '837': { city: 'Yong Peng', state: 'Johor' },
  '840': { city: 'Muar', state: 'Johor' },
  '841': { city: 'Parit Jawa', state: 'Johor' },
  '842': { city: 'Bakri', state: 'Johor' },
  '843': { city: 'Bukit Pasir', state: 'Johor' },
  '844': { city: 'Sungai Mati', state: 'Johor' },
  '845': { city: 'Panchor', state: 'Johor' },
  '846': { city: 'Pagoh', state: 'Johor' },
  '847': { city: 'Gersik', state: 'Johor' },
  '848': { city: 'Bukit Gambir', state: 'Johor' },
  '849': { city: 'Tangkak', state: 'Johor' },
  '850': { city: 'Segamat', state: 'Johor' },
  '851': { city: 'Batu Anam', state: 'Johor' },
  '852': { city: 'Jementah', state: 'Johor' },
  '853': { city: 'Bekok', state: 'Johor' },
  '854': { city: 'Chaah / Labis', state: 'Johor' },
  '860': { city: 'Kluang', state: 'Johor' },
  '861': { city: 'Kluang', state: 'Johor' },
  '862': { city: 'Simpang Renggam', state: 'Johor' },
  '863': { city: 'Renggam', state: 'Johor' },
  '864': { city: 'Parit Raja', state: 'Johor' },
  '865': { city: 'Kahang', state: 'Johor' },
  '866': { city: 'Paloh', state: 'Johor' },
  '867': { city: 'Kahang', state: 'Johor' },
  '868': { city: 'Mersing', state: 'Johor' },
  '869': { city: 'Endau', state: 'Johor' },

  // LABUAN (87xxx)
  '870': { city: 'Labuan', state: 'Wilayah Persekutuan Labuan' },

  // SABAH (88xxx - 91xxx)
  '880': { city: 'Kota Kinabalu', state: 'Sabah' },
  '881': { city: 'Kota Kinabalu', state: 'Sabah' },
  '882': { city: 'Kota Kinabalu', state: 'Sabah' },
  '883': { city: 'Kota Kinabalu', state: 'Sabah' },
  '884': { city: 'Kota Kinabalu', state: 'Sabah' },
  '885': { city: 'Kota Kinabalu', state: 'Sabah' },
  '888': { city: 'Kota Kinabalu', state: 'Sabah' },
  '890': { city: 'Keningau', state: 'Sabah' },
  '891': { city: 'Kota Marudu', state: 'Sabah' },
  '892': { city: 'Tuaran', state: 'Sabah' },
  '893': { city: 'Ranau', state: 'Sabah' },
  '895': { city: 'Penampang', state: 'Sabah' },
  '896': { city: 'Papar', state: 'Sabah' },
  '897': { city: 'Beaufort', state: 'Sabah' },
  '898': { city: 'Sipitang / Tenom', state: 'Sabah' },
  '899': { city: 'Nabawan', state: 'Sabah' },
  '900': { city: 'Sandakan', state: 'Sabah' },
  '901': { city: 'Beluran', state: 'Sabah' },
  '902': { city: 'Kinabatangan', state: 'Sabah' },
  '903': { city: 'Sandakan', state: 'Sabah' },
  '910': { city: 'Tawau', state: 'Sabah' },
  '911': { city: 'Lahad Datu', state: 'Sabah' },
  '912': { city: 'Kunak', state: 'Sabah' },
  '913': { city: 'Semporna', state: 'Sabah' },

  // SARAWAK (93xxx - 98xxx)
  '930': { city: 'Kuching', state: 'Sarawak' },
  '931': { city: 'Kuching', state: 'Sarawak' },
  '932': { city: 'Kuching', state: 'Sarawak' },
  '933': { city: 'Kuching', state: 'Sarawak' },
  '934': { city: 'Kuching', state: 'Sarawak' },
  '940': { city: 'Bau', state: 'Sarawak' },
  '942': { city: 'Lundu', state: 'Sarawak' },
  '943': { city: 'Kota Samarahan', state: 'Sarawak' },
  '945': { city: 'Roban / Saratok', state: 'Sarawak' },
  '946': { city: 'Asajaya', state: 'Sarawak' },
  '947': { city: 'Serian', state: 'Sarawak' },
  '948': { city: 'Simunjan', state: 'Sarawak' },
  '949': { city: 'Sebuyau', state: 'Sarawak' },
  '950': { city: 'Sri Aman', state: 'Sarawak' },
  '953': { city: 'Lingga', state: 'Sarawak' },
  '954': { city: 'Saratok', state: 'Sarawak' },
  '957': { city: 'Betong', state: 'Sarawak' },
  '958': { city: 'Spaoh', state: 'Sarawak' },
  '959': { city: 'Pusa', state: 'Sarawak' },
  '960': { city: 'Sibu', state: 'Sarawak' },
  '961': { city: 'Sarikei', state: 'Sarawak' },
  '962': { city: 'Bintangor', state: 'Sarawak' },
  '963': { city: 'Dalat', state: 'Sarawak' },
  '964': { city: 'Mukah', state: 'Sarawak' },
  '965': { city: 'Matu', state: 'Sarawak' },
  '966': { city: 'Daro', state: 'Sarawak' },
  '967': { city: 'Kanowit', state: 'Sarawak' },
  '968': { city: 'Kapit', state: 'Sarawak' },
  '969': { city: 'Song', state: 'Sarawak' },
  '970': { city: 'Bintulu', state: 'Sarawak' },
  '971': { city: 'Tatau', state: 'Sarawak' },
  '972': { city: 'Sebauh', state: 'Sarawak' },
  '980': { city: 'Miri', state: 'Sarawak' },
  '981': { city: 'Lutong / Miri', state: 'Sarawak' },
  '982': { city: 'Bekenu', state: 'Sarawak' },
  '983': { city: 'Long Lama', state: 'Sarawak' },
  '985': { city: 'Limbang', state: 'Sarawak' },
  '987': { city: 'Lawas', state: 'Sarawak' },
  '988': { city: 'Sundar', state: 'Sarawak' },
};

/**
 * 2-Digit State Fallback Map
 * Guarantees that EVERY 5-digit Malaysian postcode correctly resolves to its State and default Region!
 */
const MALAYSIA_2DIGIT_FALLBACK: Record<string, { city: string; state: string }> = {
  '01': { city: 'Kangar', state: 'Perlis' },
  '02': { city: 'Arau', state: 'Perlis' },
  '05': { city: 'Alor Setar', state: 'Kedah' },
  '06': { city: 'Jitra', state: 'Kedah' },
  '07': { city: 'Langkawi', state: 'Kedah' },
  '08': { city: 'Sungai Petani', state: 'Kedah' },
  '09': { city: 'Kulim', state: 'Kedah' },
  '10': { city: 'Georgetown', state: 'Pulau Pinang' },
  '11': { city: 'Bayan Lepas', state: 'Pulau Pinang' },
  '12': { city: 'Butterworth', state: 'Pulau Pinang' },
  '13': { city: 'Kepala Batas', state: 'Pulau Pinang' },
  '14': { city: 'Bukit Mertajam', state: 'Pulau Pinang' },
  '15': { city: 'Kota Bharu', state: 'Kelantan' },
  '16': { city: 'Bachok / Pasir Puteh', state: 'Kelantan' },
  '17': { city: 'Pasir Mas / Tanah Merah', state: 'Kelantan' },
  '18': { city: 'Kuala Krai / Gua Musang', state: 'Kelantan' },
  '20': { city: 'Kuala Terengganu', state: 'Terengganu' },
  '21': { city: 'Kuala Nerus / Marang', state: 'Terengganu' },
  '22': { city: 'Besut / Jerteh', state: 'Terengganu' },
  '23': { city: 'Dungun / Paka', state: 'Terengganu' },
  '24': { city: 'Kemaman / Kerteh', state: 'Terengganu' },
  '25': { city: 'Kuantan', state: 'Pahang' },
  '26': { city: 'Pekan / Muadzam Shah', state: 'Pahang' },
  '27': { city: 'Jerantut / Lipis / Raub', state: 'Pahang' },
  '28': { city: 'Temerloh / Mentakab / Bentong', state: 'Pahang' },
  '30': { city: 'Ipoh', state: 'Perak' },
  '31': { city: 'Batu Gajah / Kampar', state: 'Perak' },
  '32': { city: 'Sitiawan / Lumut', state: 'Perak' },
  '33': { city: 'Kuala Kangsar / Gerik', state: 'Perak' },
  '34': { city: 'Taiping / Parit Buntar', state: 'Perak' },
  '35': { city: 'Tapah / Tanjung Malim', state: 'Perak' },
  '36': { city: 'Teluk Intan / Bagan Datuk', state: 'Perak' },
  '39': { city: 'Cameron Highlands', state: 'Pahang' },
  '40': { city: 'Shah Alam', state: 'Selangor' },
  '41': { city: 'Klang', state: 'Selangor' },
  '42': { city: 'Kapar / Banting / Pelabuhan Klang', state: 'Selangor' },
  '43': { city: 'Kajang / Bangi / Sepang', state: 'Selangor' },
  '44': { city: 'Kuala Kubu Bharu / Batang Kali', state: 'Selangor' },
  '45': { city: 'Kuala Selangor / Sabak Bernam', state: 'Selangor' },
  '46': { city: 'Petaling Jaya', state: 'Selangor' },
  '47': { city: 'Subang Jaya / Puchong / Petaling Jaya', state: 'Selangor' },
  '48': { city: 'Rawang / Selayang', state: 'Selangor' },
  '49': { city: 'Bukit Fraser', state: 'Pahang' },
  '50': { city: 'Kuala Lumpur', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '51': { city: 'Sentul / Segambut', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '52': { city: 'Kepong / Menjalara', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '53': { city: 'Setapak / Wangsa Maju', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '54': { city: 'Keramat / Setiawangsa', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '55': { city: 'Cheras / Pudu', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '56': { city: 'Cheras', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '57': { city: 'Bukit Jalil / Bandar Tun Razak', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '58': { city: 'Kuchai Lama / Taman Desa', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '59': { city: 'Bangsar / Pantai', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '60': { city: 'TTDI / Damansara', state: 'Wilayah Persekutuan Kuala Lumpur' },
  '62': { city: 'Putrajaya', state: 'Wilayah Persekutuan Putrajaya' },
  '63': { city: 'Cyberjaya', state: 'Selangor' },
  '69': { city: 'Genting Highlands', state: 'Pahang' },
  '70': { city: 'Seremban', state: 'Negeri Sembilan' },
  '71': { city: 'Port Dickson / Nilai / Rembau', state: 'Negeri Sembilan' },
  '72': { city: 'Kuala Pilah / Bahau', state: 'Negeri Sembilan' },
  '73': { city: 'Tampin / Gemas', state: 'Negeri Sembilan' },
  '75': { city: 'Melaka / Ayer Keroh', state: 'Melaka' },
  '76': { city: 'Durian Tunggal / Sungai Udang', state: 'Melaka' },
  '77': { city: 'Jasin / Merlimau', state: 'Melaka' },
  '78': { city: 'Alor Gajah / Masjid Tanah', state: 'Melaka' },
  '79': { city: 'Iskandar Puteri', state: 'Johor' },
  '80': { city: 'Johor Bahru', state: 'Johor' },
  '81': { city: 'Skudai / Kulai / Pasir Gudang', state: 'Johor' },
  '82': { city: 'Pontian', state: 'Johor' },
  '83': { city: 'Batu Pahat / Yong Peng', state: 'Johor' },
  '84': { city: 'Muar / Tangkak', state: 'Johor' },
  '85': { city: 'Segamat / Labis', state: 'Johor' },
  '86': { city: 'Kluang / Mersing', state: 'Johor' },
  '87': { city: 'Labuan', state: 'Wilayah Persekutuan Labuan' },
  '88': { city: 'Kota Kinabalu', state: 'Sabah' },
  '89': { city: 'Keningau / Penampang / Papar', state: 'Sabah' },
  '90': { city: 'Sandakan / Beluran', state: 'Sabah' },
  '91': { city: 'Tawau / Lahad Datu / Semporna', state: 'Sabah' },
  '93': { city: 'Kuching', state: 'Sarawak' },
  '94': { city: 'Kota Samarahan / Serian / Bau', state: 'Sarawak' },
  '95': { city: 'Sri Aman / Betong / Saratok', state: 'Sarawak' },
  '96': { city: 'Sibu / Sarikei / Mukah / Kapit', state: 'Sarawak' },
  '97': { city: 'Bintulu / Tatau', state: 'Sarawak' },
  '98': { city: 'Miri / Limbang / Lawas', state: 'Sarawak' },
};

export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url);
  const rawCode = searchParams.get('code')?.trim() || '';
  const cleanCode = rawCode.replace(/\D/g, '').slice(0, 5);

  if (!cleanCode || cleanCode.length < 2) {
    return NextResponse.json(
      { success: false, message: 'Sila masukkan sekurang-kurangnya 2 digit poskod.' },
      { status: 400 }
    );
  }

  // 1. Try 3-digit prefix lookup
  const prefix3 = cleanCode.slice(0, 3);
  let result = MALAYSIA_POSTCODE_MAP[prefix3];

  // 2. If not found, try 2-digit state fallback
  if (!result) {
    const prefix2 = cleanCode.slice(0, 2);
    result = MALAYSIA_2DIGIT_FALLBACK[prefix2];
  }

  if (!result) {
    return NextResponse.json(
      { success: false, message: 'Poskod tidak dikenali dalam senarai Malaysia.' },
      { status: 404 }
    );
  }

  return NextResponse.json({
    success: true,
    postcode: cleanCode,
    city: result.city,
    state: result.state,
  });
}
